/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

public class AbortoProcedimientoMotivo extends javax.swing.JFrame {

    public AbortoProcedimientoMotivo () {
        initComponents();
        this.setLocationRelativeTo(null);  // Se ejecuta en el medio de la pantalla
        mostrarMotivos(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelProcedimiento = new javax.swing.JLabel();
        jLabelDegrade1 = new javax.swing.JLabel();
        jLabelLogoUNLa = new javax.swing.JLabel();
        jComboBoxProcedimientos = new javax.swing.JComboBox<>();
        jLabelDegrade2 = new javax.swing.JLabel();
        jLabelMotivo = new javax.swing.JLabel();
        jLabelDegrade3 = new javax.swing.JLabel();
        jButtonSiguiente = new javax.swing.JButton();
        jComboBoxMotivos = new javax.swing.JComboBox<>();
        jLabelDegrade4 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(850, 700));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("TFL"), this, org.jdesktop.beansbinding.BeanProperty.create("title"));
        bindingGroup.addBinding(binding);

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Calibri", 2, 16)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("DETERMINADOR DE SANCIONES PARA DELITOS CONTRA LAS PERSONAS, EL HONOR Y LA INTEGRIDAD SEXUAL");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 17, 720, 20));

        jLabelProcedimiento.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelProcedimiento.setText("Indique el procedimiento mediante el cual se realizó el delito:");
        getContentPane().add(jLabelProcedimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 20));

        jLabelDegrade1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDegrade1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade1.png"))); // NOI18N
        getContentPane().add(jLabelDegrade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 840, 40));

        jLabelLogoUNLa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IconUNLa30x30.png"))); // NOI18N
        jLabelLogoUNLa.setText("jLabel1");
        getContentPane().add(jLabelLogoUNLa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jComboBoxProcedimientos.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxProcedimientos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el procedimiento", "Sin consentimiento de la víctima", "Con consentimiento de la víctima", "Con consentimiento de un representante legal de la víctima (si la víctima es demente)", "Accidentalmente por violencia", "Mujer consciente que causa su propio aborto" }));
        jComboBoxProcedimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProcedimientosActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxProcedimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabelDegrade2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        jLabelDegrade2.setText("jLabel1");
        getContentPane().add(jLabelDegrade2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 670, 50));

        jLabelMotivo.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelMotivo.setText("Indique el motivo por el cual se cometió el delito:");
        getContentPane().add(jLabelMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 20));

        jLabelDegrade3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDegrade3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade1.png"))); // NOI18N
        getContentPane().add(jLabelDegrade3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 840, 40));

        jButtonSiguiente.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jButtonSiguiente.setText("Siguiente");
        jButtonSiguiente.setEnabled(false);
        jButtonSiguiente.setMaximumSize(new java.awt.Dimension(39, 29));
        jButtonSiguiente.setMinimumSize(new java.awt.Dimension(39, 29));
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 660, 150, 50));

        jComboBoxMotivos.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxMotivos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el motivo", "Abuso de la profesión (del victimario)", "Evitar un peligro para la vida o salud de la mujer embarazada, que no pueda ser evitado por otros medios", "Embarazo proveniente de una violación o de un atentado al pudor sobre una mujer demente", "Otro" }));
        jComboBoxMotivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMotivosActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxMotivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabelDegrade4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        jLabelDegrade4.setText("jLabel1");
        getContentPane().add(jLabelDegrade4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 810, 50));

        jLabelFondo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 740));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mostrarMotivos(boolean mostrar) {
        jLabelDegrade3.setVisible(mostrar);
        jLabelDegrade4.setVisible(mostrar);
        jLabelMotivo.setVisible(mostrar);
        jComboBoxMotivos.setVisible(mostrar);
    }
    
    private void jComboBoxProcedimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProcedimientosActionPerformed
        if (((String)jComboBoxProcedimientos.getSelectedItem() == "Sin consentimiento de la víctima")
            || ((String)jComboBoxProcedimientos.getSelectedItem() == "Con consentimiento de la víctima")
            || ((String)jComboBoxProcedimientos.getSelectedItem() == "Con consentimiento de un representante legal de la víctima (si la víctima es demente)")) {
            mostrarMotivos(true);
            jComboBoxMotivos.setSelectedItem("Seleccione el motivo");
            jButtonSiguiente.setEnabled(false);
        }
        if (((String)jComboBoxProcedimientos.getSelectedItem() == "Accidentalmente por violencia")
            || ((String)jComboBoxProcedimientos.getSelectedItem() == "Mujer consciente que causa su propio aborto")) {
            mostrarMotivos(false);
            jButtonSiguiente.setEnabled(true);            
        } 
        if ((String)jComboBoxProcedimientos.getSelectedItem() == "Seleccione el procedimiento") {
            mostrarMotivos(false);
            jComboBoxMotivos.setSelectedItem("Seleccione el motivo");
            jButtonSiguiente.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBoxProcedimientosActionPerformed

    private void jComboBoxMotivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMotivosActionPerformed
        if ((String)jComboBoxMotivos.getSelectedItem() != "Seleccione el motivo") {
            jButtonSiguiente.setEnabled(true);
        }
        if ((String)jComboBoxMotivos.getSelectedItem() == "Seleccione el motivo") {
            jButtonSiguiente.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBoxMotivosActionPerformed

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        if ((((String)jComboBoxProcedimientos.getSelectedItem() == "Sin consentimiento de la víctima")
            || ((String)jComboBoxProcedimientos.getSelectedItem() == "Con consentimiento de la víctima")
            || ((String)jComboBoxProcedimientos.getSelectedItem() == "Con consentimiento de un representante legal de la víctima (si la víctima es demente)"))
            && ((String)jComboBoxMotivos.getSelectedItem() != "Otro")) {
            AbortoVictimario a = new AbortoVictimario();
            a.setVisible(true);
            this.setVisible(false);        
        }        
        if ((((String)jComboBoxProcedimientos.getSelectedItem() == "Sin consentimiento de la víctima")
            || ((String)jComboBoxProcedimientos.getSelectedItem() == "Con consentimiento de la víctima")
            || ((String)jComboBoxProcedimientos.getSelectedItem() == "Con consentimiento de un representante legal de la víctima (si la víctima es demente)"))
            && ((String)jComboBoxMotivos.getSelectedItem() == "Otro")) {
            AbortoMedico a = new AbortoMedico();
            a.setVisible(true);
            this.setVisible(false);        
        }    
        if ((String)jComboBoxProcedimientos.getSelectedItem() == "Accidentalmente por violencia") {
            AbortoVictimario a = new AbortoVictimario();
            a.setVisible(true);
            this.setVisible(false);               
        }
        if ((String)jComboBoxProcedimientos.getSelectedItem() == "Mujer consciente que causa su propio aborto") {
            AbortoMujerCausaSuAborto a = new AbortoMujerCausaSuAborto();
            a.setVisible(true);
            this.setVisible(false);            
        } 
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    public static String getProcedimiento() {
        String resultado = (String)jComboBoxProcedimientos.getSelectedItem();
        switch (resultado) {    
            case "Sin consentimiento de la víctima":
                resultado = "Sin consentimiento de la victima";
                break;                
            case "Con consentimiento de la víctima":
                resultado = "Con consentimiento de la victima";
                break;        
            case "Con consentimiento de un representante legal de la víctima (si la víctima es demente)":
                resultado = "Con consentimiento de un representante legal de la victima (si la victima es demente)";
                break;     
        }
        return resultado;
    }    
    
    public static String getMotivo() {
        String resultado = (String)jComboBoxMotivos.getSelectedItem();
        switch (resultado) {    
            case "Abuso de la profesión (del victimario)":
                resultado = "Abuso de la profesion (del victimario)";
                break; 
            case "Embarazo proveniente de una violación o de un atentado al pudor sobre una mujer demente":
                resultado = "Embarazo proveniente de una violacion o de un atentado al pudor sobre una mujer demente";
                break; 
        }
        return resultado;
    }   

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonSiguiente;
    private static javax.swing.JComboBox<String> jComboBoxMotivos;
    private static javax.swing.JComboBox<String> jComboBoxProcedimientos;
    private javax.swing.JLabel jLabelDegrade1;
    private javax.swing.JLabel jLabelDegrade2;
    private javax.swing.JLabel jLabelDegrade3;
    private javax.swing.JLabel jLabelDegrade4;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLogoUNLa;
    private javax.swing.JLabel jLabelMotivo;
    private javax.swing.JLabel jLabelProcedimiento;
    private javax.swing.JLabel jLabelTitulo;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
