/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

public class AbusoSexualVictimarioVictima extends javax.swing.JFrame {
    
    public AbusoSexualVictimarioVictima () {
        initComponents();
        this.setLocationRelativeTo(null);  // Se ejecuta en el medio de la pantalla

        mostrarDatosVictima1(false);
        mostrarDatosVictima2(false);
        mostrarEstado(false);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelDatosVictimario = new javax.swing.JLabel();
        jLabelEdadVictimario = new javax.swing.JLabel();
        jLabelLogoUNLa = new javax.swing.JLabel();
        jTextFieldNombreApellidoVictimario = new javax.swing.JTextField();
        jTextFieldDNIVictimario = new javax.swing.JTextField();
        jTextFieldEdadVictimario = new javax.swing.JTextField();
        jButtonConfirmarDatosVictimario = new javax.swing.JButton();
        jLabelDNIVictimario = new javax.swing.JLabel();
        jLabelNombreApellidoVictimario = new javax.swing.JLabel();
        jButtonSiguiente = new javax.swing.JButton();
        jLabelDegrade2 = new javax.swing.JLabel();
        jLabelDegrade1 = new javax.swing.JLabel();
        jLabelDNIVictima = new javax.swing.JLabel();
        jButtonConfirmarDatosVictima = new javax.swing.JButton();
        jLabelNombreApellidoVictima = new javax.swing.JLabel();
        jTextFieldNombreApellidoVictima = new javax.swing.JTextField();
        jTextFieldEdadVictima = new javax.swing.JTextField();
        jTextFieldDNIVictima = new javax.swing.JTextField();
        jLabelEdadVictima1 = new javax.swing.JLabel();
        jLabelEdadVictima2 = new javax.swing.JLabel();
        jLabelDatosVictima = new javax.swing.JLabel();
        jLabelDegrade3 = new javax.swing.JLabel();
        jLabelDegrade4 = new javax.swing.JLabel();
        jLabelEstadoVictima = new javax.swing.JLabel();
        jLabelDegrade5 = new javax.swing.JLabel();
        jRadioButtonConVidaSinLesiones = new javax.swing.JRadioButton();
        jRadioButtonConVidaConLesiones = new javax.swing.JRadioButton();
        jRadioButtonFallecido = new javax.swing.JRadioButton();
        jLabelDegrade6 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("TFL"), this, org.jdesktop.beansbinding.BeanProperty.create("title"));
        bindingGroup.addBinding(binding);

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Calibri", 2, 16)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("DETERMINADOR DE SANCIONES PARA DELITOS CONTRA LAS PERSONAS, EL HONOR Y LA INTEGRIDAD SEXUAL");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 17, 720, 20));

        jLabelDatosVictimario.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDatosVictimario.setText("Ingrese los datos del victimario:");
        getContentPane().add(jLabelDatosVictimario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 20));

        jLabelEdadVictimario.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEdadVictimario.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelEdadVictimario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdadVictimario.setText("Edad:");
        getContentPane().add(jLabelEdadVictimario, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, -1));

        jLabelLogoUNLa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IconUNLa30x30.png"))); // NOI18N
        jLabelLogoUNLa.setText("jLabel1");
        getContentPane().add(jLabelLogoUNLa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jTextFieldNombreApellidoVictimario.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldNombreApellidoVictimario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreApellidoVictimarioActionPerformed(evt);
            }
        });
        jTextFieldNombreApellidoVictimario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreApellidoVictimarioKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldNombreApellidoVictimario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 270, 30));

        jTextFieldDNIVictimario.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldDNIVictimario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDNIVictimarioActionPerformed(evt);
            }
        });
        jTextFieldDNIVictimario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDNIVictimarioKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldDNIVictimario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 100, 30));

        jTextFieldEdadVictimario.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldEdadVictimario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEdadVictimarioKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldEdadVictimario, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 90, 30));

        jButtonConfirmarDatosVictimario.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jButtonConfirmarDatosVictimario.setText("Confirmar datos");
        jButtonConfirmarDatosVictimario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarDatosVictimarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirmarDatosVictimario, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 170, 50));

        jLabelDNIVictimario.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDNIVictimario.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelDNIVictimario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDNIVictimario.setText("DNI:");
        getContentPane().add(jLabelDNIVictimario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        jLabelNombreApellidoVictimario.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNombreApellidoVictimario.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelNombreApellidoVictimario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreApellidoVictimario.setText("Nombre y apellido:");
        getContentPane().add(jLabelNombreApellidoVictimario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jButtonSiguiente.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jButtonSiguiente.setText("Siguiente");
        jButtonSiguiente.setEnabled(false);
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 660, 150, 50));

        jLabelDegrade2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        jLabelDegrade2.setText("jLabel1");
        getContentPane().add(jLabelDegrade2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 540, 110));

        jLabelDegrade1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDegrade1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade1.png"))); // NOI18N
        getContentPane().add(jLabelDegrade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 840, 40));

        jLabelDNIVictima.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDNIVictima.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelDNIVictima.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDNIVictima.setText("DNI:");
        getContentPane().add(jLabelDNIVictima, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, -1));

        jButtonConfirmarDatosVictima.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jButtonConfirmarDatosVictima.setText("Confirmar datos");
        jButtonConfirmarDatosVictima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarDatosVictimaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirmarDatosVictima, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 170, 50));

        jLabelNombreApellidoVictima.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNombreApellidoVictima.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelNombreApellidoVictima.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreApellidoVictima.setText("Nombre y apellido:");
        getContentPane().add(jLabelNombreApellidoVictima, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jTextFieldNombreApellidoVictima.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldNombreApellidoVictima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreApellidoVictimaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombreApellidoVictima, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 270, 30));

        jTextFieldEdadVictima.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldEdadVictima.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEdadVictimaKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldEdadVictima, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 90, 30));

        jTextFieldDNIVictima.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldDNIVictima.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDNIVictimaKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldDNIVictima, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 100, 30));

        jLabelEdadVictima1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEdadVictima1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelEdadVictima1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdadVictima1.setText("Edad:");
        getContentPane().add(jLabelEdadVictima1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, -1, -1));

        jLabelEdadVictima2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEdadVictima2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelEdadVictima2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdadVictima2.setText("(13 a 17)");
        getContentPane().add(jLabelEdadVictima2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 405, -1, -1));

        jLabelDatosVictima.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDatosVictima.setText("Ingrese los datos de la víctima:");
        getContentPane().add(jLabelDatosVictima, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 20));

        jLabelDegrade3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDegrade3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade1.png"))); // NOI18N
        getContentPane().add(jLabelDegrade3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 840, 40));

        jLabelDegrade4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        jLabelDegrade4.setText("jLabel1");
        getContentPane().add(jLabelDegrade4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 540, 110));

        jLabelEstadoVictima.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelEstadoVictima.setText("Indique el estado de la víctima:");
        getContentPane().add(jLabelEstadoVictima, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, 20));

        jLabelDegrade5.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDegrade5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade1.png"))); // NOI18N
        getContentPane().add(jLabelDegrade5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 840, 40));

        buttonGroup1.add(jRadioButtonConVidaSinLesiones);
        jRadioButtonConVidaSinLesiones.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButtonConVidaSinLesiones.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonConVidaSinLesiones.setText("Con vida, sin lesiones");
        jRadioButtonConVidaSinLesiones.setContentAreaFilled(false);
        jRadioButtonConVidaSinLesiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonConVidaSinLesionesActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonConVidaSinLesiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        buttonGroup1.add(jRadioButtonConVidaConLesiones);
        jRadioButtonConVidaConLesiones.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButtonConVidaConLesiones.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonConVidaConLesiones.setText("Con vida, con lesiones");
        jRadioButtonConVidaConLesiones.setContentAreaFilled(false);
        jRadioButtonConVidaConLesiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonConVidaConLesionesActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonConVidaConLesiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, -1, -1));

        buttonGroup1.add(jRadioButtonFallecido);
        jRadioButtonFallecido.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButtonFallecido.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonFallecido.setText("Fallecido");
        jRadioButtonFallecido.setContentAreaFilled(false);
        jRadioButtonFallecido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFallecidoActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonFallecido, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, -1, -1));

        jLabelDegrade6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        jLabelDegrade6.setText("jLabel1");
        getContentPane().add(jLabelDegrade6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 500, 30));

        jLabelFondo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 740));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mostrarDatosVictima1(boolean mostrar) {
        jLabelDegrade3.setVisible(mostrar);
        jLabelDatosVictima.setVisible(mostrar);
        jLabelDegrade4.setVisible(mostrar);
        jLabelNombreApellidoVictima.setVisible(mostrar);
        jTextFieldNombreApellidoVictima.setVisible(mostrar);
        jLabelDNIVictima.setVisible(mostrar);
        jTextFieldDNIVictima.setVisible(mostrar);
        jLabelEdadVictima1.setVisible(mostrar);
        jTextFieldEdadVictima.setVisible(mostrar);
        jButtonConfirmarDatosVictima.setVisible(mostrar);
    }

    public void mostrarDatosVictima2(boolean mostrar) {
        jLabelDegrade3.setVisible(mostrar);
        jLabelDatosVictima.setVisible(mostrar);
        jLabelDegrade4.setVisible(mostrar);
        jLabelNombreApellidoVictima.setVisible(mostrar);
        jTextFieldNombreApellidoVictima.setVisible(mostrar);
        jLabelDNIVictima.setVisible(mostrar);
        jTextFieldDNIVictima.setVisible(mostrar);
        jLabelEdadVictima1.setVisible(mostrar);
        jLabelEdadVictima2.setVisible(mostrar);
        jTextFieldEdadVictima.setVisible(mostrar);
        jButtonConfirmarDatosVictima.setVisible(mostrar);
    }

    
    public void mostrarEstado(boolean mostrar) {
        jLabelDegrade5.setVisible(mostrar);
        jLabelEstadoVictima.setVisible(mostrar);
        jLabelDegrade6.setVisible(mostrar);
        jRadioButtonConVidaSinLesiones.setVisible(mostrar);
        jRadioButtonConVidaConLesiones.setVisible(mostrar);
        jRadioButtonFallecido.setVisible(mostrar);    
    }

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        Condena a = new Condena();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void jTextFieldNombreApellidoVictimarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreApellidoVictimarioActionPerformed

    }//GEN-LAST:event_jTextFieldNombreApellidoVictimarioActionPerformed

    private void jTextFieldDNIVictimarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDNIVictimarioKeyTyped
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_jTextFieldDNIVictimarioKeyTyped

    private void jTextFieldEdadVictimarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEdadVictimarioKeyTyped
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_jTextFieldEdadVictimarioKeyTyped

    private void jTextFieldNombreApellidoVictimarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreApellidoVictimarioKeyTyped
//        char c = evt.getKeyChar();
//        if ((c<'a' || c>'z' ) && (c<'A' || c>'Z') && (c==' ')) evt.consume();
    }//GEN-LAST:event_jTextFieldNombreApellidoVictimarioKeyTyped

    private void jTextFieldDNIVictimarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDNIVictimarioActionPerformed

    }//GEN-LAST:event_jTextFieldDNIVictimarioActionPerformed

    private void jButtonConfirmarDatosVictimarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarDatosVictimarioActionPerformed
        if ((!jTextFieldNombreApellidoVictimario.getText().isEmpty()) && (!jTextFieldDNIVictimario.getText().isEmpty()) && (!jTextFieldEdadVictimario.getText().isEmpty())) {
            if (Index.getConsentimiento() == "No") {
                mostrarDatosVictima1(true);                
            }
            if (Index.getConsentimiento() == "Si") {
                mostrarDatosVictima2(true);                
            }
            jTextFieldNombreApellidoVictimario.setEnabled(false);
            jTextFieldDNIVictimario.setEnabled(false);
            jTextFieldEdadVictimario.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonConfirmarDatosVictimarioActionPerformed

    private void jTextFieldNombreApellidoVictimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreApellidoVictimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreApellidoVictimaActionPerformed

    private void jButtonConfirmarDatosVictimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarDatosVictimaActionPerformed
        if ((!jTextFieldNombreApellidoVictima.getText().isEmpty()) && (!jTextFieldDNIVictima.getText().isEmpty()) && (!jTextFieldEdadVictima.getText().isEmpty())) {
            mostrarEstado(true);
            jButtonConfirmarDatosVictima.setVisible(false);
            jTextFieldNombreApellidoVictima.setEnabled(false);
            jTextFieldDNIVictima.setEnabled(false);
            jTextFieldEdadVictima.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonConfirmarDatosVictimaActionPerformed

    private void jTextFieldDNIVictimaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDNIVictimaKeyTyped
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();

    }//GEN-LAST:event_jTextFieldDNIVictimaKeyTyped

    private void jTextFieldEdadVictimaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEdadVictimaKeyTyped
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_jTextFieldEdadVictimaKeyTyped

    private void jRadioButtonConVidaSinLesionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonConVidaSinLesionesActionPerformed
        if (jRadioButtonConVidaSinLesiones.isSelected()) {
            jButtonSiguiente.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonConVidaSinLesionesActionPerformed

    private void jRadioButtonConVidaConLesionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonConVidaConLesionesActionPerformed
        if (jRadioButtonConVidaConLesiones.isSelected()) {
            jButtonSiguiente.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonConVidaConLesionesActionPerformed

    private void jRadioButtonFallecidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFallecidoActionPerformed
        if (jRadioButtonFallecido.isSelected()) {
            jButtonSiguiente.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonFallecidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    public static String getNombreApellidoVictimario() {
        return (String)jTextFieldNombreApellidoVictimario.getText();
    }
    
    public static int getDNIVictimario() {
        return Integer.parseInt(jTextFieldDNIVictimario.getText());
    }
    
    public static int getEdadVictimario() {
        return Integer.parseInt(jTextFieldEdadVictimario.getText());
    }

    public static String getRol() {
        return "Ejecutor";
    }
    
    public static String getNombreApellidoVictima() {
        return (String)jTextFieldNombreApellidoVictima.getText();
    }
    
    public static int getDNIVictima() {
        return Integer.parseInt(jTextFieldDNIVictima.getText());
    }
    
    public static int getEdadVictima() {
        return Integer.parseInt(jTextFieldEdadVictima.getText());
    }  

    public static String getEstado() {
        String resultado = "";
        if (jRadioButtonConVidaSinLesiones.isSelected()) {
            resultado = "Con vida, sin lesiones";
        }
        if (jRadioButtonConVidaConLesiones.isSelected()) {
            resultado = "Con vida, con lesiones";
        }
        if (jRadioButtonFallecido.isSelected()) {
            resultado = "Fallecido";
        }
        return resultado;
    }       
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonConfirmarDatosVictima;
    private javax.swing.JButton jButtonConfirmarDatosVictimario;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JLabel jLabelDNIVictima;
    private javax.swing.JLabel jLabelDNIVictimario;
    private javax.swing.JLabel jLabelDatosVictima;
    private javax.swing.JLabel jLabelDatosVictimario;
    private javax.swing.JLabel jLabelDegrade1;
    private javax.swing.JLabel jLabelDegrade2;
    private javax.swing.JLabel jLabelDegrade3;
    private javax.swing.JLabel jLabelDegrade4;
    private javax.swing.JLabel jLabelDegrade5;
    private javax.swing.JLabel jLabelDegrade6;
    private javax.swing.JLabel jLabelEdadVictima1;
    private javax.swing.JLabel jLabelEdadVictima2;
    private javax.swing.JLabel jLabelEdadVictimario;
    private javax.swing.JLabel jLabelEstadoVictima;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLogoUNLa;
    private javax.swing.JLabel jLabelNombreApellidoVictima;
    private javax.swing.JLabel jLabelNombreApellidoVictimario;
    private javax.swing.JLabel jLabelTitulo;
    private static javax.swing.JRadioButton jRadioButtonConVidaConLesiones;
    private static javax.swing.JRadioButton jRadioButtonConVidaSinLesiones;
    private static javax.swing.JRadioButton jRadioButtonFallecido;
    private static javax.swing.JTextField jTextFieldDNIVictima;
    private static javax.swing.JTextField jTextFieldDNIVictimario;
    private static javax.swing.JTextField jTextFieldEdadVictima;
    private static javax.swing.JTextField jTextFieldEdadVictimario;
    private static javax.swing.JTextField jTextFieldNombreApellidoVictima;
    private static javax.swing.JTextField jTextFieldNombreApellidoVictimario;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
