/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

public class RiñaVictimarioVictima extends javax.swing.JFrame {
    
    public RiñaVictimarioVictima () {
        initComponents();
        this.setLocationRelativeTo(null);  // Se ejecuta en el medio de la pantalla

        mostrarDatosVictimario(false);
        mostrarRelacion(false);
        mostrarDatosVictima(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelDatosVictimario = new javax.swing.JLabel();
        jLabelCantidadVictimarios3 = new javax.swing.JLabel();
        jLabelEdadVictimario = new javax.swing.JLabel();
        jLabelDegrade3 = new javax.swing.JLabel();
        jLabelLogoUNLa = new javax.swing.JLabel();
        jLabelCantidadVictimarios2 = new javax.swing.JLabel();
        jTextFieldCantidadVictimarios = new javax.swing.JTextField();
        jLabelDegrade2 = new javax.swing.JLabel();
        jButtonConfirmarDatos1 = new javax.swing.JButton();
        jTextFieldNombreApellidoVictimario = new javax.swing.JTextField();
        jTextFieldDNIVictimario = new javax.swing.JTextField();
        jTextFieldEdadVictimario = new javax.swing.JTextField();
        jButtonConfirmarDatos2 = new javax.swing.JButton();
        jLabelDNIVictimario = new javax.swing.JLabel();
        jLabelNombreApellidoVictimario = new javax.swing.JLabel();
        jButtonSiguiente = new javax.swing.JButton();
        jLabelDegrade4 = new javax.swing.JLabel();
        jLabelRelacionConVictima = new javax.swing.JLabel();
        jRadioButtonOtra = new javax.swing.JRadioButton();
        jRadioButtonParejaExPareja = new javax.swing.JRadioButton();
        jRadioButtonConyugeExConyuge = new javax.swing.JRadioButton();
        jRadioButtonAscendenteDescendente = new javax.swing.JRadioButton();
        jLabelDegrade5 = new javax.swing.JLabel();
        jLabelDegrade6 = new javax.swing.JLabel();
        jLabelCantidadVictimarios1 = new javax.swing.JLabel();
        jLabelDegrade1 = new javax.swing.JLabel();
        jLabelDNIVictima = new javax.swing.JLabel();
        jButtonConfirmarDatos3 = new javax.swing.JButton();
        jLabelNombreApellidoVictima = new javax.swing.JLabel();
        jTextFieldNombreApellidoVictima = new javax.swing.JTextField();
        jTextFieldEdadVictima = new javax.swing.JTextField();
        jTextFieldDNIVictima = new javax.swing.JTextField();
        jLabelEdadVictima = new javax.swing.JLabel();
        jLabelDatosVictima = new javax.swing.JLabel();
        jLabelDegrade7 = new javax.swing.JLabel();
        jLabelDegrade8 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("TFL"), this, org.jdesktop.beansbinding.BeanProperty.create("title"));
        bindingGroup.addBinding(binding);

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Calibri", 2, 16)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("DETERMINADOR DE SANCIONES PARA DELITOS CONTRA LAS PERSONAS, EL HONOR Y LA INTEGRIDAD SEXUAL");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 17, 720, 20));

        jLabelDatosVictimario.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDatosVictimario.setText("Ingrese los datos del victimario:");
        getContentPane().add(jLabelDatosVictimario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 20));

        jLabelCantidadVictimarios3.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCantidadVictimarios3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelCantidadVictimarios3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCantidadVictimarios3.setText("(Al menos 2)");
        getContentPane().add(jLabelCantidadVictimarios3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 155, -1, -1));

        jLabelEdadVictimario.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEdadVictimario.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelEdadVictimario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdadVictimario.setText("Edad:");
        getContentPane().add(jLabelEdadVictimario, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, -1));

        jLabelDegrade3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDegrade3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade1.png"))); // NOI18N
        getContentPane().add(jLabelDegrade3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 840, 40));

        jLabelLogoUNLa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IconUNLa30x30.png"))); // NOI18N
        jLabelLogoUNLa.setText("jLabel1");
        getContentPane().add(jLabelLogoUNLa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabelCantidadVictimarios2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCantidadVictimarios2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelCantidadVictimarios2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCantidadVictimarios2.setText("Cantidad de victimarios:");
        getContentPane().add(jLabelCantidadVictimarios2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 135, -1, -1));

        jTextFieldCantidadVictimarios.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldCantidadVictimarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCantidadVictimariosKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldCantidadVictimarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 70, 30));

        jLabelDegrade2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        jLabelDegrade2.setText("jLabel1");
        getContentPane().add(jLabelDegrade2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 300, 50));

        jButtonConfirmarDatos1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jButtonConfirmarDatos1.setText("Confirmar datos");
        jButtonConfirmarDatos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarDatos1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirmarDatos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 170, 50));

        jTextFieldNombreApellidoVictimario.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldNombreApellidoVictimario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreApellidoVictimarioActionPerformed(evt);
            }
        });
        jTextFieldNombreApellidoVictimario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreApellidoVictimarioKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldNombreApellidoVictimario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 270, 30));

        jTextFieldDNIVictimario.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldDNIVictimario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDNIVictimarioActionPerformed(evt);
            }
        });
        jTextFieldDNIVictimario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDNIVictimarioKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldDNIVictimario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 100, 30));

        jTextFieldEdadVictimario.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldEdadVictimario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEdadVictimarioKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldEdadVictimario, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 90, 30));

        jButtonConfirmarDatos2.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jButtonConfirmarDatos2.setText("Confirmar datos");
        jButtonConfirmarDatos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarDatos2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirmarDatos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 170, 50));

        jLabelDNIVictimario.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDNIVictimario.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelDNIVictimario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDNIVictimario.setText("DNI:");
        getContentPane().add(jLabelDNIVictimario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        jLabelNombreApellidoVictimario.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNombreApellidoVictimario.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelNombreApellidoVictimario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreApellidoVictimario.setText("Nombre y apellido:");
        getContentPane().add(jLabelNombreApellidoVictimario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jButtonSiguiente.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jButtonSiguiente.setText("Siguiente");
        jButtonSiguiente.setEnabled(false);
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 660, 150, 50));

        jLabelDegrade4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        jLabelDegrade4.setText("jLabel1");
        getContentPane().add(jLabelDegrade4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 540, 110));

        jLabelRelacionConVictima.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelRelacionConVictima.setText("Seleccione la relación del victimario con alguna de las víctimas:");
        getContentPane().add(jLabelRelacionConVictima, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, 20));

        buttonGroup1.add(jRadioButtonOtra);
        jRadioButtonOtra.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButtonOtra.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonOtra.setText("Otra");
        jRadioButtonOtra.setContentAreaFilled(false);
        jRadioButtonOtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOtraActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonOtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, 70, -1));

        buttonGroup1.add(jRadioButtonParejaExPareja);
        jRadioButtonParejaExPareja.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButtonParejaExPareja.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonParejaExPareja.setText("Pareja/Ex pareja");
        jRadioButtonParejaExPareja.setContentAreaFilled(false);
        jRadioButtonParejaExPareja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonParejaExParejaActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonParejaExPareja, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 150, -1));

        buttonGroup1.add(jRadioButtonConyugeExConyuge);
        jRadioButtonConyugeExConyuge.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButtonConyugeExConyuge.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonConyugeExConyuge.setText("Cónyuge/Ex cónyuge");
        jRadioButtonConyugeExConyuge.setContentAreaFilled(false);
        jRadioButtonConyugeExConyuge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonConyugeExConyugeActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonConyugeExConyuge, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 190, -1));

        buttonGroup1.add(jRadioButtonAscendenteDescendente);
        jRadioButtonAscendenteDescendente.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButtonAscendenteDescendente.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonAscendenteDescendente.setText("Ascendente/Descendente");
        jRadioButtonAscendenteDescendente.setContentAreaFilled(false);
        jRadioButtonAscendenteDescendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAscendenteDescendenteActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonAscendenteDescendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 220, -1));

        jLabelDegrade5.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDegrade5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade1.png"))); // NOI18N
        getContentPane().add(jLabelDegrade5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 840, 40));

        jLabelDegrade6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        jLabelDegrade6.setText("jLabel1");
        getContentPane().add(jLabelDegrade6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 650, 30));

        jLabelCantidadVictimarios1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelCantidadVictimarios1.setText("¿Cuántos victimarios involucrados hay en el caso?");
        getContentPane().add(jLabelCantidadVictimarios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 20));

        jLabelDegrade1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDegrade1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade1.png"))); // NOI18N
        getContentPane().add(jLabelDegrade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 840, 40));

        jLabelDNIVictima.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDNIVictima.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelDNIVictima.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDNIVictima.setText("DNI:");
        getContentPane().add(jLabelDNIVictima, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 580, -1, -1));

        jButtonConfirmarDatos3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jButtonConfirmarDatos3.setText("Confirmar datos");
        jButtonConfirmarDatos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarDatos3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirmarDatos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 590, 170, 50));

        jLabelNombreApellidoVictima.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNombreApellidoVictima.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelNombreApellidoVictima.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreApellidoVictima.setText("Nombre y apellido:");
        getContentPane().add(jLabelNombreApellidoVictima, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, -1, -1));

        jTextFieldNombreApellidoVictima.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldNombreApellidoVictima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreApellidoVictimaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombreApellidoVictima, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, 270, 30));

        jTextFieldEdadVictima.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldEdadVictima.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEdadVictimaKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldEdadVictima, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 610, 90, 30));

        jTextFieldDNIVictima.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldDNIVictima.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDNIVictimaKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldDNIVictima, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 610, 100, 30));

        jLabelEdadVictima.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEdadVictima.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelEdadVictima.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdadVictima.setText("Edad:");
        getContentPane().add(jLabelEdadVictima, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 580, -1, -1));

        jLabelDatosVictima.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDatosVictima.setText("Ingrese los datos de la víctima:");
        getContentPane().add(jLabelDatosVictima, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, 20));

        jLabelDegrade7.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDegrade7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade1.png"))); // NOI18N
        getContentPane().add(jLabelDegrade7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 840, 40));

        jLabelDegrade8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        jLabelDegrade8.setText("jLabel1");
        getContentPane().add(jLabelDegrade8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 540, 110));

        jLabelFondo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 740));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mostrarDatosVictimario (boolean mostrar) {
        jLabelDegrade3.setVisible(mostrar);
        jLabelDatosVictimario.setVisible(mostrar);
        jLabelDegrade4.setVisible(mostrar);
        jLabelNombreApellidoVictimario.setVisible(mostrar);
        jTextFieldNombreApellidoVictimario.setVisible(mostrar);
        jLabelDNIVictimario.setVisible(mostrar);
        jTextFieldDNIVictimario.setVisible(mostrar);
        jLabelEdadVictimario.setVisible(mostrar);
        jTextFieldEdadVictimario.setVisible(mostrar);
        jButtonConfirmarDatos2.setVisible(mostrar);
    }
    
    public void mostrarRelacion (boolean mostrar) {
        jLabelDegrade5.setVisible(mostrar);
        jLabelRelacionConVictima.setVisible(mostrar);
        jLabelDegrade6.setVisible(mostrar);
        jRadioButtonAscendenteDescendente.setVisible(mostrar);
        jRadioButtonConyugeExConyuge.setVisible(mostrar);
        jRadioButtonParejaExPareja.setVisible(mostrar);
        jRadioButtonOtra.setVisible(mostrar);
    }

    public void mostrarDatosVictima (boolean mostrar) {
        jLabelDegrade7.setVisible(mostrar);
        jLabelDatosVictima.setVisible(mostrar);
        jLabelDegrade8.setVisible(mostrar);
        jLabelNombreApellidoVictima.setVisible(mostrar);
        jTextFieldNombreApellidoVictima.setVisible(mostrar);
        jLabelDNIVictima.setVisible(mostrar);
        jTextFieldDNIVictima.setVisible(mostrar);
        jLabelEdadVictima.setVisible(mostrar);
        jTextFieldEdadVictima.setVisible(mostrar);
        jButtonConfirmarDatos3.setVisible(mostrar);
    }
    
    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        Condena a = new Condena();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void jTextFieldNombreApellidoVictimarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreApellidoVictimarioActionPerformed

    }//GEN-LAST:event_jTextFieldNombreApellidoVictimarioActionPerformed

    private void jRadioButtonOtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOtraActionPerformed
        if (jRadioButtonOtra.isSelected()) {
            mostrarDatosVictima(true);
        }
    }//GEN-LAST:event_jRadioButtonOtraActionPerformed

    private void jRadioButtonParejaExParejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonParejaExParejaActionPerformed
        if (jRadioButtonParejaExPareja.isSelected()) {
            mostrarDatosVictima(true);
        }
    }//GEN-LAST:event_jRadioButtonParejaExParejaActionPerformed

    private void jRadioButtonConyugeExConyugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonConyugeExConyugeActionPerformed
        if (jRadioButtonConyugeExConyuge.isSelected()) {
            mostrarDatosVictima(true);
        }
    }//GEN-LAST:event_jRadioButtonConyugeExConyugeActionPerformed

    private void jRadioButtonAscendenteDescendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAscendenteDescendenteActionPerformed
        if (jRadioButtonAscendenteDescendente.isSelected()) {
            mostrarDatosVictima(true);
        }
    }//GEN-LAST:event_jRadioButtonAscendenteDescendenteActionPerformed

    private void jTextFieldDNIVictimarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDNIVictimarioKeyTyped
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_jTextFieldDNIVictimarioKeyTyped

    private void jTextFieldEdadVictimarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEdadVictimarioKeyTyped
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_jTextFieldEdadVictimarioKeyTyped

    private void jTextFieldNombreApellidoVictimarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreApellidoVictimarioKeyTyped
//        char c = evt.getKeyChar();
//        if ((c<'a' || c>'z' ) && (c<'A' || c>'Z') && (c==' ')) evt.consume();
    }//GEN-LAST:event_jTextFieldNombreApellidoVictimarioKeyTyped

    private void jTextFieldDNIVictimarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDNIVictimarioActionPerformed

    }//GEN-LAST:event_jTextFieldDNIVictimarioActionPerformed

    private void jButtonConfirmarDatos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarDatos2ActionPerformed
        if ((!jTextFieldNombreApellidoVictimario.getText().isEmpty()) && (!jTextFieldDNIVictimario.getText().isEmpty()) && (!jTextFieldEdadVictimario.getText().isEmpty())) {
            jButtonConfirmarDatos2.setVisible(false);
            mostrarRelacion(true);
            jTextFieldNombreApellidoVictimario.setEnabled(false);
            jTextFieldDNIVictimario.setEnabled(false);
            jTextFieldEdadVictimario.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonConfirmarDatos2ActionPerformed

    private void jTextFieldNombreApellidoVictimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreApellidoVictimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreApellidoVictimaActionPerformed

    private void jButtonConfirmarDatos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarDatos3ActionPerformed
        if ((!jTextFieldNombreApellidoVictima.getText().isEmpty()) && (!jTextFieldDNIVictima.getText().isEmpty()) && (!jTextFieldEdadVictima.getText().isEmpty())) {
            jButtonConfirmarDatos3.setVisible(false);
            jButtonSiguiente.setEnabled(true);
            jTextFieldNombreApellidoVictima.setEnabled(false);
            jTextFieldDNIVictima.setEnabled(false);
            jTextFieldEdadVictima.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonConfirmarDatos3ActionPerformed

    private void jTextFieldCantidadVictimariosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCantidadVictimariosKeyTyped
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_jTextFieldCantidadVictimariosKeyTyped

    private void jButtonConfirmarDatos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarDatos1ActionPerformed
        if ((!jTextFieldCantidadVictimarios.getText().isEmpty())) {
            jTextFieldCantidadVictimarios.setEnabled(false);
            jButtonConfirmarDatos1.setVisible(false);
            mostrarDatosVictimario(true);
        }
    }//GEN-LAST:event_jButtonConfirmarDatos1ActionPerformed

    private void jTextFieldDNIVictimaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDNIVictimaKeyTyped
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_jTextFieldDNIVictimaKeyTyped

    private void jTextFieldEdadVictimaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEdadVictimaKeyTyped
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_jTextFieldEdadVictimaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    public static int getCantidadVictimarios() {
        return Integer.parseInt(jTextFieldCantidadVictimarios.getText());
    }

    public static String getNombreApellidoVictimario() {
        return (String)jTextFieldNombreApellidoVictimario.getText();
    }
    
    public static int getDNIVictimario() {
        return Integer.parseInt(jTextFieldDNIVictimario.getText());
    }
    
    public static int getEdadVictimario() {
        return Integer.parseInt(jTextFieldEdadVictimario.getText());
    }

    public static String getRelacionConVictima() {
        String resultado = "";
        if (jRadioButtonAscendenteDescendente.isSelected()) {
           resultado = "Ascendente o descendente"; 
        }
        if (jRadioButtonConyugeExConyuge.isSelected()) {
            resultado = "Conyuge o ex conyuge";
        }
        if (jRadioButtonParejaExPareja.isSelected()) {
            resultado = "Pareja o ex pareja";
        }
        if (jRadioButtonOtra.isSelected()) {
            resultado = "Otra";
        }
        return resultado;
    }    

    public static String getRol() {
        return "Ejecutor";
    }
    
    public static String getNombreApellidoVictima() {
        return (String)jTextFieldNombreApellidoVictima.getText();
    }
    
    public static int getDNIVictima() {
        return Integer.parseInt(jTextFieldDNIVictima.getText());
    }
    
    public static int getEdadVictima() {
        return Integer.parseInt(jTextFieldEdadVictima.getText());
    }   
    
    public static String getEstado() {
        String resultado = "";
        if (Index.getTipoDelitoRiña() == "Homicidio en rinia") {
            resultado = "Fallecido";
        }
        if (Index.getTipoDelitoRiña() == "Lesion en rinia") {
            resultado = "Con vida, con lesiones";
        }
        return resultado;
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonConfirmarDatos1;
    private javax.swing.JButton jButtonConfirmarDatos2;
    private javax.swing.JButton jButtonConfirmarDatos3;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JLabel jLabelCantidadVictimarios1;
    private javax.swing.JLabel jLabelCantidadVictimarios2;
    private javax.swing.JLabel jLabelCantidadVictimarios3;
    private javax.swing.JLabel jLabelDNIVictima;
    private javax.swing.JLabel jLabelDNIVictimario;
    private javax.swing.JLabel jLabelDatosVictima;
    private javax.swing.JLabel jLabelDatosVictimario;
    private javax.swing.JLabel jLabelDegrade1;
    private javax.swing.JLabel jLabelDegrade2;
    private javax.swing.JLabel jLabelDegrade3;
    private javax.swing.JLabel jLabelDegrade4;
    private javax.swing.JLabel jLabelDegrade5;
    private javax.swing.JLabel jLabelDegrade6;
    private javax.swing.JLabel jLabelDegrade7;
    private javax.swing.JLabel jLabelDegrade8;
    private javax.swing.JLabel jLabelEdadVictima;
    private javax.swing.JLabel jLabelEdadVictimario;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLogoUNLa;
    private javax.swing.JLabel jLabelNombreApellidoVictima;
    private javax.swing.JLabel jLabelNombreApellidoVictimario;
    private javax.swing.JLabel jLabelRelacionConVictima;
    private javax.swing.JLabel jLabelTitulo;
    private static javax.swing.JRadioButton jRadioButtonAscendenteDescendente;
    private static javax.swing.JRadioButton jRadioButtonConyugeExConyuge;
    private static javax.swing.JRadioButton jRadioButtonOtra;
    private static javax.swing.JRadioButton jRadioButtonParejaExPareja;
    private static javax.swing.JTextField jTextFieldCantidadVictimarios;
    private static javax.swing.JTextField jTextFieldDNIVictima;
    private static javax.swing.JTextField jTextFieldDNIVictimario;
    private static javax.swing.JTextField jTextFieldEdadVictima;
    private static javax.swing.JTextField jTextFieldEdadVictimario;
    private static javax.swing.JTextField jTextFieldNombreApellidoVictima;
    private static javax.swing.JTextField jTextFieldNombreApellidoVictimario;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
