/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

public class AbusoSexual extends javax.swing.JFrame {

    public AbusoSexual () {
        initComponents();
        this.setLocationRelativeTo(null);  // Se ejecuta en el medio de la pantalla

        if (Index.getConsentimiento() == "No") {
            mostrarSituacion2(false);
            mostrarSituacion1(true);
        }
        if (Index.getConsentimiento() == "Si") {
            mostrarSituacion1(false);
            mostrarSituacion2(true);
        }
        
        mostrarAgravantes1(false);
        mostrarAgravantes2(false);
        mostrarAgravantes3(false);
        mostrarProcedimientos(false);
        mostrarRelacion1(false);
        mostrarRelacion2(false);
        mostrarCantidadVictimarios1(false);
        mostrarCantidadVictimarios2(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLabelLogoUNLa = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelSituacion = new javax.swing.JLabel();
        jLabelDegrade1 = new javax.swing.JLabel();
        jComboBoxTipoAbusoSexual1 = new javax.swing.JComboBox<>();
        jComboBoxTipoAbusoSexual2 = new javax.swing.JComboBox<>();
        jLabelDegrade2 = new javax.swing.JLabel();
        jComboBoxRelaciones1 = new javax.swing.JComboBox<>();
        jComboBoxRelaciones2 = new javax.swing.JComboBox<>();
        jComboBoxAgravantes1 = new javax.swing.JComboBox<>();
        jComboBoxAgravantes2 = new javax.swing.JComboBox<>();
        jComboBoxAgravantes3 = new javax.swing.JComboBox<>();
        jLabelProcedimiento = new javax.swing.JLabel();
        jComboBoxProcedimientos = new javax.swing.JComboBox<>();
        jLabelDegrade4 = new javax.swing.JLabel();
        jLabelAgravantes = new javax.swing.JLabel();
        jLabelDegrade3 = new javax.swing.JLabel();
        jLabelDegrade5 = new javax.swing.JLabel();
        jLabelDegrade6 = new javax.swing.JLabel();
        jLabelRelacionConVictima = new javax.swing.JLabel();
        jLabelDegrade7 = new javax.swing.JLabel();
        jLabelDegrade8 = new javax.swing.JLabel();
        jButtonSiguiente = new javax.swing.JButton();
        jLabelCantidadVictimarios1 = new javax.swing.JLabel();
        jLabelDegrade9 = new javax.swing.JLabel();
        jLabelCantidadVictimarios2 = new javax.swing.JLabel();
        jLabelCantidadVictimarios3 = new javax.swing.JLabel();
        jTextFieldCantidadVictimarios = new javax.swing.JTextField();
        jLabelDegrade10 = new javax.swing.JLabel();
        jButtonConfirmarDatos = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("TFL"), this, org.jdesktop.beansbinding.BeanProperty.create("title"));
        bindingGroup.addBinding(binding);

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogoUNLa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IconUNLa30x30.png"))); // NOI18N
        jLabelLogoUNLa.setText("jLabel1");
        getContentPane().add(jLabelLogoUNLa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabelTitulo.setFont(new java.awt.Font("Calibri", 2, 16)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("DETERMINADOR DE SANCIONES PARA DELITOS CONTRA LAS PERSONAS, EL HONOR Y LA INTEGRIDAD SEXUAL");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 17, 720, 20));

        jLabelSituacion.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelSituacion.setText("Indique la situacion sucedida:");
        getContentPane().add(jLabelSituacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 20));

        jLabelDegrade1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDegrade1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade1.png"))); // NOI18N
        getContentPane().add(jLabelDegrade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 840, 40));

        jComboBoxTipoAbusoSexual1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxTipoAbusoSexual1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la situación", "Abuso sexual", "Abuso sexual gravemente ultrajante", "Abuso sexual agravado por acceso carnal" }));
        jComboBoxTipoAbusoSexual1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoAbusoSexual1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxTipoAbusoSexual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 460, -1));

        jComboBoxTipoAbusoSexual2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxTipoAbusoSexual2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la situación", "Abuso sexual gravemente ultrajante", "Abuso sexual agravado por acceso carnal" }));
        jComboBoxTipoAbusoSexual2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoAbusoSexual2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxTipoAbusoSexual2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 460, -1));

        jLabelDegrade2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        jLabelDegrade2.setText("jLabel1");
        getContentPane().add(jLabelDegrade2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 480, 50));

        jComboBoxRelaciones1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxRelaciones1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la relación", "Ascendente/Descendente", "Afín en línea recta", "Hermano", "Tutor" }));
        jComboBoxRelaciones1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRelaciones1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxRelaciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        jComboBoxRelaciones2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxRelaciones2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la relación", "Ascendente/Descendente", "Cónyuge/Ex cónyuge", "Pareja/Ex pareja", "Otra" }));
        jComboBoxRelaciones2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRelaciones2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxRelaciones2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        jComboBoxAgravantes1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxAgravantes1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el agravante", "Abuso sexual agravado por el resultado", "Abuso sexual agravado por el parentesco con la víctima", "Abuso sexual agravado por la calidad del autor", "Abuso sexual agravado por el número de autores", "Abuso sexual agravado por el medio empleado", "Abuso sexual agravado por la edad y situación de convivencia preexistente con la víctima", "Ninguno de los anteriores" }));
        jComboBoxAgravantes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAgravantes1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxAgravantes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jComboBoxAgravantes2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxAgravantes2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el agravante", "Abuso sexual agravado por el resultado", "Abuso sexual agravado por el parentesco con la víctima", "Abuso sexual agravado por la calidad del autor", "Abuso sexual agravado por la enfermedad del autor", "Abuso sexual agravado por el número de autores", "Abuso sexual agravado por el medio empleado", "Abuso sexual agravado por la edad y situación de convivencia preexistente con la víctima", "Ninguno de los anteriores" }));
        jComboBoxAgravantes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAgravantes2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxAgravantes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jComboBoxAgravantes3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxAgravantes3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el agravante", "Abuso sexual agravado por el resultado", "Abuso sexual agravado por el parentesco con la víctima", "Abuso sexual agravado por la calidad del autor", "Abuso sexual agravado por la enfermedad del autor", "Abuso sexual agravado por la edad y situación de convivencia preexistente con la víctima", "Ninguno de los anteriores" }));
        jComboBoxAgravantes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAgravantes3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxAgravantes3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabelProcedimiento.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelProcedimiento.setText("Seleccione el procedimiento mediante el cual se realizo el delito:");
        getContentPane().add(jLabelProcedimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, 20));

        jComboBoxProcedimientos.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxProcedimientos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el procedimiento", "Violencia", "Amenaza", "Abuso coactivo o intimidatorio de una relación de dependencia, de autoridad o de poder", "Aprovechamiento de que la víctima por cualquier causa no haya podido consentir libremente la acción" }));
        jComboBoxProcedimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProcedimientosActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxProcedimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jLabelDegrade4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        jLabelDegrade4.setText("jLabel1");
        getContentPane().add(jLabelDegrade4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 710, 50));

        jLabelAgravantes.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelAgravantes.setText("¿Ocurrió alguno de los siguientes agravantes?");
        getContentPane().add(jLabelAgravantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 20));

        jLabelDegrade3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDegrade3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade1.png"))); // NOI18N
        getContentPane().add(jLabelDegrade3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 840, 40));

        jLabelDegrade5.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDegrade5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade1.png"))); // NOI18N
        getContentPane().add(jLabelDegrade5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 840, 40));

        jLabelDegrade6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        jLabelDegrade6.setText("jLabel1");
        getContentPane().add(jLabelDegrade6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 800, 50));

        jLabelRelacionConVictima.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelRelacionConVictima.setText("Seleccione la relación del victimario con alguna de las víctimas:");
        getContentPane().add(jLabelRelacionConVictima, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, 20));

        jLabelDegrade7.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDegrade7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade1.png"))); // NOI18N
        getContentPane().add(jLabelDegrade7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 840, 40));

        jLabelDegrade8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        jLabelDegrade8.setText("jLabel1");
        getContentPane().add(jLabelDegrade8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 240, 50));

        jButtonSiguiente.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jButtonSiguiente.setText("Siguiente");
        jButtonSiguiente.setEnabled(false);
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 660, 150, 50));

        jLabelCantidadVictimarios1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelCantidadVictimarios1.setText("¿Cuántos victimarios involucrados hay en el caso?");
        getContentPane().add(jLabelCantidadVictimarios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, 20));

        jLabelDegrade9.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDegrade9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade1.png"))); // NOI18N
        getContentPane().add(jLabelDegrade9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 840, 40));

        jLabelCantidadVictimarios2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCantidadVictimarios2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelCantidadVictimarios2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCantidadVictimarios2.setText("Cantidad de victimarios:");
        getContentPane().add(jLabelCantidadVictimarios2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 595, -1, -1));

        jLabelCantidadVictimarios3.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCantidadVictimarios3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelCantidadVictimarios3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCantidadVictimarios3.setText("(Al menos 2)");
        getContentPane().add(jLabelCantidadVictimarios3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 615, -1, -1));

        jTextFieldCantidadVictimarios.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldCantidadVictimarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantidadVictimariosActionPerformed(evt);
            }
        });
        jTextFieldCantidadVictimarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCantidadVictimariosKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldCantidadVictimarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 600, 70, 30));

        jLabelDegrade10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        jLabelDegrade10.setText("jLabel1");
        getContentPane().add(jLabelDegrade10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 300, 70));

        jButtonConfirmarDatos.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jButtonConfirmarDatos.setText("Confirmar datos");
        jButtonConfirmarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarDatosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirmarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 590, 170, 50));

        jLabelFondo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 740));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mostrarSituacion1(boolean mostrar) {
        jLabelDegrade1.setVisible(mostrar);
        jLabelSituacion.setVisible(mostrar);
        jLabelDegrade2.setVisible(mostrar);
        jComboBoxTipoAbusoSexual1.setVisible(mostrar);
    }
    
    public void mostrarSituacion2(boolean mostrar) {
        jLabelDegrade1.setVisible(mostrar);
        jLabelSituacion.setVisible(mostrar);
        jLabelDegrade2.setVisible(mostrar);
        jComboBoxTipoAbusoSexual2.setVisible(mostrar);
    }    

    public void mostrarAgravantes1(boolean mostrar) {
        jLabelDegrade3.setVisible(mostrar);
        jLabelAgravantes.setVisible(mostrar);
        jLabelDegrade4.setVisible(mostrar);
        jComboBoxAgravantes1.setVisible(mostrar);
    }
    
    public void mostrarAgravantes2(boolean mostrar) {
        jLabelDegrade3.setVisible(mostrar);
        jLabelAgravantes.setVisible(mostrar);
        jLabelDegrade4.setVisible(mostrar);
        jComboBoxAgravantes2.setVisible(mostrar);
    }
        
    public void mostrarAgravantes3(boolean mostrar) {
        jLabelDegrade3.setVisible(mostrar);
        jLabelAgravantes.setVisible(mostrar);
        jLabelDegrade4.setVisible(mostrar);
        jComboBoxAgravantes3.setVisible(mostrar);
    }

    public void mostrarProcedimientos(boolean mostrar) {
        jLabelDegrade5.setVisible(mostrar);
        jLabelProcedimiento.setVisible(mostrar);
        jLabelDegrade6.setVisible(mostrar);
        jComboBoxProcedimientos.setVisible(mostrar);
    }

    public void mostrarRelacion1(boolean mostrar) {
        jLabelDegrade7.setVisible(mostrar);
        jLabelRelacionConVictima.setVisible(mostrar);
        jLabelDegrade8.setVisible(mostrar);
        jComboBoxRelaciones1.setVisible(mostrar);
    }
    
    public void mostrarRelacion2(boolean mostrar) {
        jLabelDegrade7.setVisible(mostrar);
        jLabelRelacionConVictima.setVisible(mostrar);
        jLabelDegrade8.setVisible(mostrar);
        jComboBoxRelaciones2.setVisible(mostrar);
    }    

    public void mostrarCantidadVictimarios1(boolean mostrar) {
        jLabelDegrade9.setVisible(mostrar);
        jLabelCantidadVictimarios1.setVisible(mostrar);
        jLabelDegrade10.setVisible(mostrar);
        jLabelCantidadVictimarios2.setVisible(mostrar);
        jTextFieldCantidadVictimarios.setVisible(mostrar);
        jButtonConfirmarDatos.setVisible(mostrar);
        jLabelCantidadVictimarios3.setVisible(mostrar);
    }
    
    public void mostrarCantidadVictimarios2(boolean mostrar) {
        jLabelDegrade9.setVisible(mostrar);
        jLabelCantidadVictimarios1.setVisible(mostrar);
        jLabelDegrade10.setVisible(mostrar);
        jLabelCantidadVictimarios2.setVisible(mostrar);
        jTextFieldCantidadVictimarios.setVisible(mostrar);
        jButtonConfirmarDatos.setVisible(mostrar);    
    }
    
    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        AbusoSexualVictimarioVictima a = new AbusoSexualVictimarioVictima();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void jComboBoxRelaciones1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRelaciones1ActionPerformed
        if ((String)jComboBoxRelaciones1.getSelectedItem() != "Seleccione la relación") {
            jComboBoxRelaciones1.setEnabled(false);
            if (((String)jComboBoxAgravantes1.getSelectedItem() == "Abuso sexual agravado por el número de autores") ||
                ((String)jComboBoxAgravantes2.getSelectedItem() == "Abuso sexual agravado por el número de autores") ||
                ((String)jComboBoxAgravantes3.getSelectedItem() == "Abuso sexual agravado por el número de autores")) {
                mostrarCantidadVictimarios1(true);
            }  
            if ((((String)jComboBoxAgravantes1.getSelectedItem() != "Seleccione el agravante") &&
                ((String)jComboBoxAgravantes1.getSelectedItem() != "Abuso sexual agravado por el número de autores"))
                ||    
                (((String)jComboBoxAgravantes2.getSelectedItem() != "Seleccione el agravante") &&
                ((String)jComboBoxAgravantes2.getSelectedItem() != "Abuso sexual agravado por el número de autores"))
                ||    
                (((String)jComboBoxAgravantes3.getSelectedItem() != "Seleccione el agravante") &&
                ((String)jComboBoxAgravantes3.getSelectedItem() != "Abuso sexual agravado por el número de autores"))        
                ) {
                mostrarCantidadVictimarios2(true);
            } 
//            if (((String)jComboBoxTipoAbusoSexual1.getSelectedItem() != "Seleccione la situación")
//                && ((String)jComboBoxAgravantes1.getSelectedItem() != "Seleccione el agravante")
//                && ((String)jComboBoxProcedimientos.getSelectedItem() != "Seleccione el procedimiento")
//                && (!jTextFieldCantidadVictimarios.isEnabled())
//                ) {
//                jButtonSiguiente.setEnabled(true);
//            }
        }
//        if ((String)jComboBoxRelaciones1.getSelectedItem() == "Seleccione la relación") {
//            jButtonSiguiente.setEnabled(false);
//        }        
    }//GEN-LAST:event_jComboBoxRelaciones1ActionPerformed

    private void jComboBoxTipoAbusoSexual1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoAbusoSexual1ActionPerformed
        if ((String)jComboBoxTipoAbusoSexual1.getSelectedItem() != "Seleccione la situación") {
            jComboBoxTipoAbusoSexual1.setEnabled(false);
            if ((String)jComboBoxTipoAbusoSexual1.getSelectedItem() == "Abuso sexual") {
                mostrarAgravantes1(true);                
            }
            if (((String)jComboBoxTipoAbusoSexual1.getSelectedItem() == "Abuso sexual gravemente ultrajante") || ((String)jComboBoxTipoAbusoSexual1.getSelectedItem() == "Abuso sexual agravado por acceso carnal")) {
                mostrarAgravantes2(true);                
            }

//            if (((String)jComboBoxAgravantes.getSelectedItem() != "Seleccione el agravante")
//                && ((String)jComboBoxProcedimientos.getSelectedItem() != "Seleccione el procedimiento")
//                && (((String)jComboBoxRelaciones1.getSelectedItem() != "Seleccione la relación") || ((String)jComboBoxRelaciones2.getSelectedItem() != "Seleccione la relación")) 
//                && (!jTextFieldCantidadVictimarios.isEnabled())        
//                ) {
//                jButtonSiguiente.setEnabled(true);
//            }
        }
//        if ((String)jComboBoxTipoAbusoSexual1.getSelectedItem() == "Seleccione la situación") {
//            jButtonSiguiente.setEnabled(false);
//        }        
    }//GEN-LAST:event_jComboBoxTipoAbusoSexual1ActionPerformed

    private void jComboBoxProcedimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProcedimientosActionPerformed
        if ((String)jComboBoxProcedimientos.getSelectedItem() != "Seleccione el procedimiento") {
            jComboBoxProcedimientos.setEnabled(false);
            if ((String)jComboBoxProcedimientos.getSelectedItem() == "Abuso sexual agravado por el parentesco con la víctima") {
                jComboBoxRelaciones1.setSelectedItem("Seleccione la relación");
                jComboBoxRelaciones2.setSelectedItem("Seleccione la relación");
                mostrarRelacion2(false);
                mostrarRelacion1(true);
//                if (((String)jComboBoxTipoAbusoSexual1.getSelectedItem() != "Seleccione la situación")
//                    && ((String)jComboBoxAgravantes.getSelectedItem() != "Seleccione el agravante")
//                    && (((String)jComboBoxRelaciones1.getSelectedItem() != "Seleccione la relación") || ((String)jComboBoxRelaciones2.getSelectedItem() != "Seleccione la relación")) 
//                    && (!jTextFieldCantidadVictimarios.isEnabled())
//                    ) {
//                    jButtonSiguiente.setEnabled(true);
//                }
            }
            if ((String)jComboBoxProcedimientos.getSelectedItem() != "Abuso sexual agravado por el parentesco con la víctima") {
                jComboBoxRelaciones1.setSelectedItem("Seleccione la relación");
                jComboBoxRelaciones2.setSelectedItem("Seleccione la relación");
                mostrarRelacion1(false);
                mostrarRelacion2(true);
            }
        }
//        if ((String)jComboBoxProcedimientos.getSelectedItem() == "Seleccione el procedimiento") {
//            jButtonSiguiente.setEnabled(false);
//        }        
    }//GEN-LAST:event_jComboBoxProcedimientosActionPerformed

    private void jComboBoxAgravantes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAgravantes1ActionPerformed
        if ((String)jComboBoxAgravantes1.getSelectedItem() != "Seleccione el agravante") {
            jComboBoxAgravantes1.setEnabled(false);
            mostrarProcedimientos(true);
        }
    }//GEN-LAST:event_jComboBoxAgravantes1ActionPerformed

    private void jComboBoxRelaciones2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRelaciones2ActionPerformed
        if ((String)jComboBoxRelaciones2.getSelectedItem() != "Seleccione la relación") {
            jComboBoxRelaciones2.setEnabled(false);
            if (((String)jComboBoxAgravantes1.getSelectedItem() == "Abuso sexual agravado por el número de autores") ||
                ((String)jComboBoxAgravantes2.getSelectedItem() == "Abuso sexual agravado por el número de autores") ||
                ((String)jComboBoxAgravantes3.getSelectedItem() == "Abuso sexual agravado por el número de autores")) {
                mostrarCantidadVictimarios1(true);
            }  
            if ((((String)jComboBoxAgravantes1.getSelectedItem() != "Seleccione el agravante") &&
                ((String)jComboBoxAgravantes1.getSelectedItem() != "Abuso sexual agravado por el número de autores")) ||
                (((String)jComboBoxAgravantes2.getSelectedItem() != "Seleccione el agravante") &&
                ((String)jComboBoxAgravantes2.getSelectedItem() != "Abuso sexual agravado por el número de autores")) ||    
                (((String)jComboBoxAgravantes3.getSelectedItem() != "Seleccione el agravante") &&
                ((String)jComboBoxAgravantes3.getSelectedItem() != "Abuso sexual agravado por el número de autores"))) {
                mostrarCantidadVictimarios2(true);
            }
//            if (((String)jComboBoxTipoAbusoSexual1.getSelectedItem() != "Seleccione la situación")
//                && ((String)jComboBoxAgravantes.getSelectedItem() != "Seleccione el agravante")
//                && ((String)jComboBoxProcedimientos.getSelectedItem() != "Seleccione el procedimiento")
//                && (!jTextFieldCantidadVictimarios.isEnabled())
//                ) {
//                jButtonSiguiente.setEnabled(true);
//            }
        }
//        if ((String)jComboBoxRelaciones2.getSelectedItem() == "Seleccione la relación") {
//            jButtonSiguiente.setEnabled(false);
//        }        
    }//GEN-LAST:event_jComboBoxRelaciones2ActionPerformed

    private void jTextFieldCantidadVictimariosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCantidadVictimariosKeyTyped
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_jTextFieldCantidadVictimariosKeyTyped

    private void jButtonConfirmarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarDatosActionPerformed
        if ((!jTextFieldCantidadVictimarios.getText().isEmpty())) {
            jTextFieldCantidadVictimarios.setEnabled(false);
            jButtonConfirmarDatos.setVisible(false);
            jButtonSiguiente.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonConfirmarDatosActionPerformed

    private void jTextFieldCantidadVictimariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantidadVictimariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCantidadVictimariosActionPerformed

    private void jComboBoxTipoAbusoSexual2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoAbusoSexual2ActionPerformed
        if ((String)jComboBoxTipoAbusoSexual2.getSelectedItem() != "Seleccione la situación") {
            jComboBoxTipoAbusoSexual2.setEnabled(false);
            mostrarAgravantes3(true);
//            if (((String)jComboBoxAgravantes.getSelectedItem() != "Seleccione el agravante")
//                && ((String)jComboBoxProcedimientos.getSelectedItem() != "Seleccione el procedimiento")
//                && (((String)jComboBoxRelaciones1.getSelectedItem() != "Seleccione la relación") || ((String)jComboBoxRelaciones2.getSelectedItem() != "Seleccione la relación")) 
//                && (!jTextFieldCantidadVictimarios.isEnabled())        
//                ) {
//                jButtonSiguiente.setEnabled(true);
//            }
        }
//        if ((String)jComboBoxTipoAbusoSexual1.getSelectedItem() == "Seleccione la situación") {
//            jButtonSiguiente.setEnabled(false);
//        }      
    }//GEN-LAST:event_jComboBoxTipoAbusoSexual2ActionPerformed

    private void jComboBoxAgravantes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAgravantes2ActionPerformed
        if ((String)jComboBoxAgravantes2.getSelectedItem() != "Seleccione el agravante") {
            jComboBoxAgravantes2.setEnabled(false);
            mostrarProcedimientos(true);
        }
    }//GEN-LAST:event_jComboBoxAgravantes2ActionPerformed

    private void jComboBoxAgravantes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAgravantes3ActionPerformed
        if ((String)jComboBoxAgravantes3.getSelectedItem() != "Seleccione el agravante") {
            jComboBoxAgravantes3.setEnabled(false);
            mostrarProcedimientos(true);
        }
    }//GEN-LAST:event_jComboBoxAgravantes3ActionPerformed

    public static String getDelito() {
        String resultado = "";
        if (Index.getConsentimiento() == "No") {
            if ((String)jComboBoxTipoAbusoSexual1.getSelectedItem() == "Abuso sexual") {
                resultado = (String)jComboBoxAgravantes1.getSelectedItem();
                switch (resultado) {
                    case "Abuso sexual agravado por el parentesco con la víctima":
                        resultado = "Abuso sexual agravado por el parentesco con la victima";
                        break;
                    case "Abuso sexual agravado por el número de autores":
                        resultado = "Abuso sexual agravado por el numero de autores";
                        break;
                    case "Abuso sexual agravado por la edad y situación de convivencia preexistente con la víctima":
                        resultado = "Abuso sexual agravado por la edad y situacion de convivencia preexistente con la victima";
                        break;
                    case "Ninguno de los anteriores":
                        resultado = "Abuso sexual";
                        break;
                }
            }
            if ((String)jComboBoxTipoAbusoSexual1.getSelectedItem() == "Abuso sexual gravemente ultrajante") {
                resultado = (String)jComboBoxAgravantes2.getSelectedItem();
                switch (resultado) {
                    case "Abuso sexual agravado por el resultado":
                        resultado = "Abuso sexual gravemente ultrajante agravado por el resultado";
                        break;
                    case "Abuso sexual agravado por el parentesco con la víctima":
                        resultado = "Abuso sexual gravemente ultrajante agravado por el parentesco con la victima";
                        break;
                    case "Abuso sexual agravado por la calidad del autor":
                        resultado = "Abuso sexual gravemente ultrajante agravado por la calidad del autor";
                        break;
                    case "Abuso sexual agravado por la enfermedad del autor":
                        resultado = "Abuso sexual gravemente ultrajante agravado por la enfermedad del autor";
                        break;
                    case "Abuso sexual agravado por el número de autores":
                        resultado = "Abuso sexual gravemente ultrajante agravado por el numero de autores";
                        break;
                    case "Abuso sexual agravado por el medio empleado":
                        resultado = "Abuso sexual gravemente ultrajante agravado por el medio empleado";
                        break;
                    case "Abuso sexual agravado por la edad y situación de convivencia preexistente con la víctima":
                        resultado = "Abuso sexual gravemente ultrajante agravado por la edad y situacion de convivencia preexistente con la victima";
                        break;  
                    case "Ninguno de los anteriores":
                        resultado = "Abuso sexual gravemente ultrajante";
                        break;  
                }                
            }
            if ((String)jComboBoxTipoAbusoSexual1.getSelectedItem() == "Abuso sexual agravado por acceso carnal") {
                resultado = (String)jComboBoxAgravantes2.getSelectedItem();
                switch (resultado) {
                    case "Abuso sexual agravado por el resultado":
                        resultado = "Abuso sexual agravado por acceso carnal y por el resultado";
                        break;
                    case "Abuso sexual agravado por el parentesco con la víctima":
                        resultado = "Abuso sexual agravado por acceso carnal y por el parentesco con la victima";
                        break;
                    case "Abuso sexual agravado por la calidad del autor":
                        resultado = "Abuso sexual agravado por acceso carnal y por la calidad del autor";
                        break;
                    case "Abuso sexual agravado por la enfermedad del autor":
                        resultado = "Abuso sexual agravado por acceso carnal y por la enfermedad del autor";
                        break;
                    case "Abuso sexual agravado por el número de autores":
                        resultado = "Abuso sexual agravado por acceso carnal y por el numero de autores";
                        break;
                    case "Abuso sexual agravado por el medio empleado":
                        resultado = "Abuso sexual agravado por acceso carnal y por el medio empleado";
                        break;
                    case "Abuso sexual agravado por la edad y situación de convivencia preexistente con la víctima":
                        resultado = "Abuso sexual agravado por acceso carnal, por la edad y situacion de convivencia preexistente con la victima";
                        break;  
                    case "Ninguno de los anteriores":
                        resultado = "Abuso sexual agravado por acceso carnal";
                        break; 
                }                 
            }
        }
        if (Index.getConsentimiento() == "Si") {
            if ((String)jComboBoxTipoAbusoSexual2.getSelectedItem() == "Abuso sexual gravemente ultrajante") {
                resultado = (String)jComboBoxAgravantes3.getSelectedItem();
                switch (resultado) {
                    case "Abuso sexual agravado por el resultado":
                        resultado = "Abuso sexual gravemente ultrajante agravado por el resultado";
                        break;
                    case "Abuso sexual agravado por el parentesco con la víctima":
                        resultado = "Abuso sexual gravemente ultrajante agravado por el parentesco con la victima";
                        break;
                    case "Abuso sexual agravado por la calidad del autor":
                        resultado = "Abuso sexual gravemente ultrajante agravado por la calidad del autor";
                        break;
                    case "Abuso sexual agravado por la enfermedad del autor":
                        resultado = "Abuso sexual gravemente ultrajante agravado por la enfermedad del autor";
                        break;
                    case "Abuso sexual agravado por la edad y situación de convivencia preexistente con la víctima":
                        resultado = "Abuso sexual gravemente ultrajante agravado por la edad y situacion de convivencia preexistente con la victima";
                        break;
                    case "Ninguno de los anteriores":
                        resultado = "Abuso sexual gravemente ultrajante";
                        break;
                }                 
            }
            if ((String)jComboBoxTipoAbusoSexual2.getSelectedItem() == "Abuso sexual agravado por acceso carnal") {
                resultado = (String)jComboBoxAgravantes3.getSelectedItem();
                switch (resultado) {
                    case "Abuso sexual agravado por el resultado":
                        resultado = "Abuso sexual agravado por acceso carnal y por el resultado";
                        break;
                    case "Abuso sexual agravado por el parentesco con la víctima":
                        resultado = "Abuso sexual agravado por acceso carnal y por el parentesco con la victima";
                        break;
                    case "Abuso sexual agravado por la calidad del autor":
                        resultado = "Abuso sexual agravado por acceso carnal y por la calidad del autor";
                        break;
                    case "Abuso sexual agravado por la enfermedad del autor":
                        resultado = "Abuso sexual agravado por acceso carnal y por la enfermedad del autor";
                        break;
                    case "Abuso sexual agravado por la edad y situación de convivencia preexistente con la víctima":
                        resultado = "Abuso sexual agravado por acceso carnal, por la edad y situacion de convivencia preexistente con la victima";
                        break;
                    case "Ninguno de los anteriores":
                        resultado = "Abuso sexual agravado por acceso carnal";
                        break;
                }                 
            }
        }
        return resultado;
    }       
    
    public static String getProcedimiento() {
        String resultado = (String)jComboBoxProcedimientos.getSelectedItem();
        switch (resultado) {    
            case "Abuso coactivo o intimidatorio de una relación de dependencia, de autoridad o de poder":
                resultado = "Abuso coactivo o intimidatorio de una relacion de dependencia, de autoridad o de poder";
                break; 
            case "Aprovechamiento de que la víctima por cualquier causa no haya podido consentir libremente la acción":
                resultado = "Aprovechamiento de que la victima por cualquier causa no haya podido consentir libremente la accion";
                break;                 
        }
        return resultado;
    }   

    public static String getRelacion() {
        String resultado = "";
        if ((String)jComboBoxProcedimientos.getSelectedItem() == "Abuso sexual agravado por el parentesco con la víctima") {
            resultado = (String)jComboBoxRelaciones1.getSelectedItem();
            switch (resultado) {    
                case "Ascendente/Descendente":
                    resultado = "Ascendente o descendente";
                    break;
                case "Afín en línea recta":
                    resultado = "Afín en linea recta";
                    break;    
            }
        }    
        if ((String)jComboBoxProcedimientos.getSelectedItem() == "Abuso sexual agravado por el parentesco con la víctima") {   
            resultado = (String)jComboBoxRelaciones2.getSelectedItem();
            switch (resultado) {    
                case "Ascendente/Descendente":
                    resultado = "Ascendente o descendente";
                    break;
                case "Conyuge/Ex cónyuge":
                    resultado = "Conyuge ex conyuge";
                    break;
                case "Pareja/Ex pareja":
                    resultado = "Pareja o ex pareja";
                    break;
            }
        }
        return resultado;
    } 
    
    public static int getCantidadVictimarios() {
        return Integer.parseInt(jTextFieldCantidadVictimarios.getText());
    }    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmarDatos;
    private javax.swing.JButton jButtonSiguiente;
    private static javax.swing.JComboBox<String> jComboBoxAgravantes1;
    private static javax.swing.JComboBox<String> jComboBoxAgravantes2;
    private static javax.swing.JComboBox<String> jComboBoxAgravantes3;
    private static javax.swing.JComboBox<String> jComboBoxProcedimientos;
    private static javax.swing.JComboBox<String> jComboBoxRelaciones1;
    private static javax.swing.JComboBox<String> jComboBoxRelaciones2;
    private static javax.swing.JComboBox<String> jComboBoxTipoAbusoSexual1;
    private static javax.swing.JComboBox<String> jComboBoxTipoAbusoSexual2;
    private javax.swing.JLabel jLabelAgravantes;
    private javax.swing.JLabel jLabelCantidadVictimarios1;
    private javax.swing.JLabel jLabelCantidadVictimarios2;
    private javax.swing.JLabel jLabelCantidadVictimarios3;
    private javax.swing.JLabel jLabelDegrade1;
    private javax.swing.JLabel jLabelDegrade10;
    private javax.swing.JLabel jLabelDegrade2;
    private javax.swing.JLabel jLabelDegrade3;
    private javax.swing.JLabel jLabelDegrade4;
    private javax.swing.JLabel jLabelDegrade5;
    private javax.swing.JLabel jLabelDegrade6;
    private javax.swing.JLabel jLabelDegrade7;
    private javax.swing.JLabel jLabelDegrade8;
    private javax.swing.JLabel jLabelDegrade9;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLogoUNLa;
    private javax.swing.JLabel jLabelProcedimiento;
    private javax.swing.JLabel jLabelRelacionConVictima;
    private javax.swing.JLabel jLabelSituacion;
    private javax.swing.JLabel jLabelTitulo;
    private static javax.swing.JTextField jTextFieldCantidadVictimarios;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
