/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

public class AbusoDeArmasVictimario extends javax.swing.JFrame {
    
    public AbusoDeArmasVictimario () {
        initComponents();
        this.setLocationRelativeTo(null);  // Se ejecuta en el medio de la pantalla

        mostrarRelacion(false);
        mostrarCantidadVictimarios(false);
        mostrarCantidadVictimas(false);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelDatosVictimario = new javax.swing.JLabel();
        jLabelEdad = new javax.swing.JLabel();
        jLabelDegrade1 = new javax.swing.JLabel();
        jLabelLogoUNLa = new javax.swing.JLabel();
        jTextFieldNombreApellido = new javax.swing.JTextField();
        jTextFieldDNI = new javax.swing.JTextField();
        jTextFieldEdad = new javax.swing.JTextField();
        jButtonConfirmarDatos1 = new javax.swing.JButton();
        jLabelDNI = new javax.swing.JLabel();
        jLabelNombreApellido = new javax.swing.JLabel();
        jButtonSiguiente = new javax.swing.JButton();
        jLabelDegrade2 = new javax.swing.JLabel();
        jLabelRelacionConVictima = new javax.swing.JLabel();
        jRadioButtonOtra = new javax.swing.JRadioButton();
        jRadioButtonParejaExPareja = new javax.swing.JRadioButton();
        jRadioButtonConyugeExConyuge = new javax.swing.JRadioButton();
        jRadioButtonAscendenteDescendente = new javax.swing.JRadioButton();
        jLabelCantidadVictimarios1 = new javax.swing.JLabel();
        jLabelDegrade3 = new javax.swing.JLabel();
        jLabelDegrade5 = new javax.swing.JLabel();
        jLabelDegrade4 = new javax.swing.JLabel();
        jLabelCantidadVictimas1 = new javax.swing.JLabel();
        jLabelDegrade7 = new javax.swing.JLabel();
        jLabelCantidadVictimarios2 = new javax.swing.JLabel();
        jTextFieldCantidadVictimarios = new javax.swing.JTextField();
        jLabelDegrade6 = new javax.swing.JLabel();
        jButtonConfirmarDatos2 = new javax.swing.JButton();
        jLabelCantidadVictimas2 = new javax.swing.JLabel();
        jTextFieldCantidadVictimas = new javax.swing.JTextField();
        jLabelDegrade8 = new javax.swing.JLabel();
        jButtonConfirmarDatos3 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("TFL"), this, org.jdesktop.beansbinding.BeanProperty.create("title"));
        bindingGroup.addBinding(binding);

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Calibri", 2, 16)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("DETERMINADOR DE SANCIONES PARA DELITOS CONTRA LAS PERSONAS, EL HONOR Y LA INTEGRIDAD SEXUAL");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 17, 720, 20));

        jLabelDatosVictimario.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDatosVictimario.setText("Ingrese los datos del victimario:");
        getContentPane().add(jLabelDatosVictimario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 20));

        jLabelEdad.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEdad.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelEdad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdad.setText("Edad:");
        getContentPane().add(jLabelEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, -1));

        jLabelDegrade1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDegrade1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade1.png"))); // NOI18N
        getContentPane().add(jLabelDegrade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 840, 40));

        jLabelLogoUNLa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IconUNLa30x30.png"))); // NOI18N
        jLabelLogoUNLa.setText("jLabel1");
        getContentPane().add(jLabelLogoUNLa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jTextFieldNombreApellido.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldNombreApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreApellidoActionPerformed(evt);
            }
        });
        jTextFieldNombreApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreApellidoKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldNombreApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 270, 30));

        jTextFieldDNI.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDNIActionPerformed(evt);
            }
        });
        jTextFieldDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDNIKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 100, 30));

        jTextFieldEdad.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEdadActionPerformed(evt);
            }
        });
        jTextFieldEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEdadKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 90, 30));

        jButtonConfirmarDatos1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jButtonConfirmarDatos1.setText("Confirmar datos");
        jButtonConfirmarDatos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarDatos1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirmarDatos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 170, 50));

        jLabelDNI.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDNI.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelDNI.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDNI.setText("DNI:");
        getContentPane().add(jLabelDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        jLabelNombreApellido.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNombreApellido.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelNombreApellido.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreApellido.setText("Nombre y apellido:");
        getContentPane().add(jLabelNombreApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jButtonSiguiente.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jButtonSiguiente.setText("Siguiente");
        jButtonSiguiente.setEnabled(false);
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 660, 150, 50));

        jLabelDegrade2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        jLabelDegrade2.setText("jLabel1");
        getContentPane().add(jLabelDegrade2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 540, 110));

        jLabelRelacionConVictima.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelRelacionConVictima.setText("Seleccione la relación del victimario con alguna de las víctimas:");
        getContentPane().add(jLabelRelacionConVictima, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 20));

        buttonGroup1.add(jRadioButtonOtra);
        jRadioButtonOtra.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButtonOtra.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonOtra.setText("Otra");
        jRadioButtonOtra.setContentAreaFilled(false);
        jRadioButtonOtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOtraActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonOtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 70, -1));

        buttonGroup1.add(jRadioButtonParejaExPareja);
        jRadioButtonParejaExPareja.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButtonParejaExPareja.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonParejaExPareja.setText("Pareja/Ex pareja");
        jRadioButtonParejaExPareja.setContentAreaFilled(false);
        jRadioButtonParejaExPareja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonParejaExParejaActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonParejaExPareja, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 150, -1));

        buttonGroup1.add(jRadioButtonConyugeExConyuge);
        jRadioButtonConyugeExConyuge.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButtonConyugeExConyuge.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonConyugeExConyuge.setText("Cónyuge/Ex cónyuge");
        jRadioButtonConyugeExConyuge.setContentAreaFilled(false);
        jRadioButtonConyugeExConyuge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonConyugeExConyugeActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonConyugeExConyuge, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 190, -1));

        buttonGroup1.add(jRadioButtonAscendenteDescendente);
        jRadioButtonAscendenteDescendente.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButtonAscendenteDescendente.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonAscendenteDescendente.setText("Ascendente/Descendente");
        jRadioButtonAscendenteDescendente.setContentAreaFilled(false);
        jRadioButtonAscendenteDescendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAscendenteDescendenteActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonAscendenteDescendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 220, -1));

        jLabelCantidadVictimarios1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelCantidadVictimarios1.setText("¿Cuántos victimarios involucrados hay en el caso?");
        getContentPane().add(jLabelCantidadVictimarios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, 20));

        jLabelDegrade3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDegrade3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade1.png"))); // NOI18N
        getContentPane().add(jLabelDegrade3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 840, 40));

        jLabelDegrade5.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDegrade5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade1.png"))); // NOI18N
        getContentPane().add(jLabelDegrade5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 840, 40));

        jLabelDegrade4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        jLabelDegrade4.setText("jLabel1");
        getContentPane().add(jLabelDegrade4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 650, 30));

        jLabelCantidadVictimas1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelCantidadVictimas1.setText("Indique la cantidad de víctimas:");
        getContentPane().add(jLabelCantidadVictimas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, 20));

        jLabelDegrade7.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDegrade7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade1.png"))); // NOI18N
        getContentPane().add(jLabelDegrade7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 840, 40));

        jLabelCantidadVictimarios2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCantidadVictimarios2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelCantidadVictimarios2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCantidadVictimarios2.setText("Cantidad de victimarios:");
        getContentPane().add(jLabelCantidadVictimarios2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        jTextFieldCantidadVictimarios.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldCantidadVictimarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCantidadVictimariosKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldCantidadVictimarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 70, 30));

        jLabelDegrade6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        jLabelDegrade6.setText("jLabel1");
        getContentPane().add(jLabelDegrade6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 300, 70));

        jButtonConfirmarDatos2.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jButtonConfirmarDatos2.setText("Confirmar datos");
        jButtonConfirmarDatos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarDatos2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirmarDatos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 170, 50));

        jLabelCantidadVictimas2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCantidadVictimas2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelCantidadVictimas2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCantidadVictimas2.setText("Cantidad de víctimas:");
        getContentPane().add(jLabelCantidadVictimas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, -1, -1));

        jTextFieldCantidadVictimas.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldCantidadVictimas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCantidadVictimasKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldCantidadVictimas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 600, 70, 30));

        jLabelDegrade8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        jLabelDegrade8.setText("jLabel1");
        getContentPane().add(jLabelDegrade8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 280, 70));

        jButtonConfirmarDatos3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jButtonConfirmarDatos3.setText("Confirmar datos");
        jButtonConfirmarDatos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarDatos3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirmarDatos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, 170, 50));

        jLabelFondo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 740));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarRelacion (boolean mostrar) {
        jLabelDegrade3.setVisible(mostrar);
        jLabelRelacionConVictima.setVisible(mostrar);
        jLabelDegrade4.setVisible(mostrar);
        jRadioButtonAscendenteDescendente.setVisible(mostrar);
        jRadioButtonConyugeExConyuge.setVisible(mostrar);
        jRadioButtonParejaExPareja.setVisible(mostrar);
        jRadioButtonOtra.setVisible(mostrar);
    }
    
    private void mostrarCantidadVictimarios (boolean mostrar) {
        jLabelDegrade5.setVisible(mostrar);
        jLabelCantidadVictimarios1.setVisible(mostrar);
        jLabelDegrade6.setVisible(mostrar);
        jLabelCantidadVictimarios2.setVisible(mostrar);
        jTextFieldCantidadVictimarios.setVisible(mostrar);
        jButtonConfirmarDatos2.setVisible(mostrar);
    }

    private void mostrarCantidadVictimas (boolean mostrar) {
        jLabelDegrade7.setVisible(mostrar);
        jLabelCantidadVictimas1.setVisible(mostrar);
        jLabelDegrade8.setVisible(mostrar);
        jLabelCantidadVictimas2.setVisible(mostrar);
        jTextFieldCantidadVictimas.setVisible(mostrar);
        jButtonConfirmarDatos3.setVisible(mostrar);        
    }
    
    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        AbusoDeArmasVictima a = new AbusoDeArmasVictima();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void jTextFieldNombreApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreApellidoActionPerformed

    }//GEN-LAST:event_jTextFieldNombreApellidoActionPerformed

    private void jRadioButtonOtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOtraActionPerformed
        if (jRadioButtonOtra.isSelected()) {
            if (jTextFieldCantidadVictimarios.isEnabled() == true) {
                mostrarCantidadVictimarios(true);        
            }
        }
    }//GEN-LAST:event_jRadioButtonOtraActionPerformed

    private void jRadioButtonParejaExParejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonParejaExParejaActionPerformed
        if (jRadioButtonParejaExPareja.isSelected()) {
            if (jTextFieldCantidadVictimarios.isEnabled() == true) {
                mostrarCantidadVictimarios(true);        
            }
        }
    }//GEN-LAST:event_jRadioButtonParejaExParejaActionPerformed

    private void jRadioButtonConyugeExConyugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonConyugeExConyugeActionPerformed
        if (jRadioButtonConyugeExConyuge.isSelected()) {
            if (jTextFieldCantidadVictimarios.isEnabled() == true) {
                mostrarCantidadVictimarios(true);        
            }
        }
    }//GEN-LAST:event_jRadioButtonConyugeExConyugeActionPerformed

    private void jRadioButtonAscendenteDescendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAscendenteDescendenteActionPerformed
        if (jRadioButtonAscendenteDescendente.isSelected()) {
            if (jTextFieldCantidadVictimarios.isEnabled() == true) {
                mostrarCantidadVictimarios(true);        
            }
        }
    }//GEN-LAST:event_jRadioButtonAscendenteDescendenteActionPerformed

    private void jTextFieldDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDNIKeyTyped
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_jTextFieldDNIKeyTyped

    private void jTextFieldEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEdadKeyTyped
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_jTextFieldEdadKeyTyped

    private void jTextFieldNombreApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreApellidoKeyTyped
//        char c = evt.getKeyChar();
//        if ((c<'a' || c>'z' ) && (c<'A' || c>'Z') && (c==' ')) evt.consume();
    }//GEN-LAST:event_jTextFieldNombreApellidoKeyTyped

    private void jTextFieldDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDNIActionPerformed

    }//GEN-LAST:event_jTextFieldDNIActionPerformed

    private void jButtonConfirmarDatos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarDatos1ActionPerformed
        if ((!jTextFieldNombreApellido.getText().isEmpty()) && (!jTextFieldDNI.getText().isEmpty()) && (!jTextFieldEdad.getText().isEmpty())) {
            mostrarRelacion(true);
            jButtonConfirmarDatos1.setVisible(false);
            jTextFieldNombreApellido.setEnabled(false);
            jTextFieldDNI.setEnabled(false);
            jTextFieldEdad.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonConfirmarDatos1ActionPerformed

    private void jTextFieldEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEdadActionPerformed

    private void jTextFieldCantidadVictimariosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCantidadVictimariosKeyTyped
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_jTextFieldCantidadVictimariosKeyTyped

    private void jButtonConfirmarDatos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarDatos2ActionPerformed
        if ((!jTextFieldCantidadVictimarios.getText().isEmpty())) {
            mostrarCantidadVictimas(true);
            jTextFieldCantidadVictimarios.setEnabled(false);
            jButtonConfirmarDatos2.setVisible(false);
        }
    }//GEN-LAST:event_jButtonConfirmarDatos2ActionPerformed

    private void jTextFieldCantidadVictimasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCantidadVictimasKeyTyped
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_jTextFieldCantidadVictimasKeyTyped

    private void jButtonConfirmarDatos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarDatos3ActionPerformed
        if ((!jTextFieldCantidadVictimas.getText().isEmpty())) {
            jTextFieldCantidadVictimas.setEnabled(false);
            jButtonConfirmarDatos3.setVisible(false);
            jButtonSiguiente.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonConfirmarDatos3ActionPerformed

    public static String getNombreApellido() {
        return (String)jTextFieldNombreApellido.getText();
    }
    
    public static int getDNI() {
        return Integer.parseInt(jTextFieldDNI.getText());
    }
    
    public static int getEdad() {
        return Integer.parseInt(jTextFieldEdad.getText());
    }

    public static String getRelacionConVictima() {
        String resultado = "";
        if (jRadioButtonAscendenteDescendente.isSelected()) {
           resultado = "Ascendente o descendente"; 
        }
        if (jRadioButtonConyugeExConyuge.isSelected()) {
            resultado = "Conyuge o ex conyuge";
        }
        if (jRadioButtonParejaExPareja.isSelected()) {
            resultado = "Pareja o ex pareja";
        }
        if (jRadioButtonOtra.isSelected()) {
            resultado = "Otra";
        }
        return resultado;
    }

    public static int getCantidadVictimarios() {
        return Integer.parseInt(jTextFieldCantidadVictimarios.getText());
    }

    public static int getCantidadVictimas() {
        return Integer.parseInt(jTextFieldCantidadVictimas.getText());
    }    
    
    public static String getRol() {
        return "Ejecutor";
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }
 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButtonConfirmarDatos1;
    private javax.swing.JButton jButtonConfirmarDatos2;
    private javax.swing.JButton jButtonConfirmarDatos3;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JLabel jLabelCantidadVictimarios1;
    private javax.swing.JLabel jLabelCantidadVictimarios2;
    private javax.swing.JLabel jLabelCantidadVictimas1;
    private javax.swing.JLabel jLabelCantidadVictimas2;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelDatosVictimario;
    private javax.swing.JLabel jLabelDegrade1;
    private javax.swing.JLabel jLabelDegrade2;
    private javax.swing.JLabel jLabelDegrade3;
    private javax.swing.JLabel jLabelDegrade4;
    private javax.swing.JLabel jLabelDegrade5;
    private javax.swing.JLabel jLabelDegrade6;
    private javax.swing.JLabel jLabelDegrade7;
    private javax.swing.JLabel jLabelDegrade8;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLogoUNLa;
    private javax.swing.JLabel jLabelNombreApellido;
    private javax.swing.JLabel jLabelRelacionConVictima;
    private javax.swing.JLabel jLabelTitulo;
    private static javax.swing.JRadioButton jRadioButtonAscendenteDescendente;
    private static javax.swing.JRadioButton jRadioButtonConyugeExConyuge;
    private static javax.swing.JRadioButton jRadioButtonOtra;
    private static javax.swing.JRadioButton jRadioButtonParejaExPareja;
    private static javax.swing.JTextField jTextFieldCantidadVictimarios;
    private static javax.swing.JTextField jTextFieldCantidadVictimas;
    private static javax.swing.JTextField jTextFieldDNI;
    private static javax.swing.JTextField jTextFieldEdad;
    private static javax.swing.JTextField jTextFieldNombreApellido;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
