/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

public class DueloSituacion extends javax.swing.JFrame {

    public DueloSituacion () {
        initComponents();
        this.setLocationRelativeTo(null);  // Se ejecuta en el medio de la pantalla

        mostrarCircExt(false);
        mostrarCantidadVictimarios(false);
        mostrarDatosVictimario(false);         
        mostrarRelacion(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabelLogoUNLa = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelSituacion = new javax.swing.JLabel();
        jLabelDegrade1 = new javax.swing.JLabel();
        jComboBoxSituaciones = new javax.swing.JComboBox<>();
        jLabelDegrade2 = new javax.swing.JLabel();
        jLabelCircExt = new javax.swing.JLabel();
        jLabelCantidadVictimarios = new javax.swing.JLabel();
        jLabelDegrade3 = new javax.swing.JLabel();
        jRadioButtonSi = new javax.swing.JRadioButton();
        jRadioButtonNo = new javax.swing.JRadioButton();
        jLabelDegrade4 = new javax.swing.JLabel();
        jTextFieldNombreApellido = new javax.swing.JTextField();
        jTextFieldDNI = new javax.swing.JTextField();
        jTextFieldEdad = new javax.swing.JTextField();
        jLabelDatosVictimario = new javax.swing.JLabel();
        jLabelEdad = new javax.swing.JLabel();
        jButtonConfirmarDatos = new javax.swing.JButton();
        jLabelDNI = new javax.swing.JLabel();
        jLabelNombreApellido = new javax.swing.JLabel();
        jLabelDegrade7 = new javax.swing.JLabel();
        jLabelRelacionConVictima = new javax.swing.JLabel();
        jRadioButtonOtra = new javax.swing.JRadioButton();
        jRadioButtonParejaExPareja = new javax.swing.JRadioButton();
        jRadioButtonConyugeExConyuge = new javax.swing.JRadioButton();
        jRadioButtonAscendenteDescendente = new javax.swing.JRadioButton();
        jLabelDegrade6 = new javax.swing.JLabel();
        jLabelDegrade8 = new javax.swing.JLabel();
        jLabelDegrade9 = new javax.swing.JLabel();
        jRadioButtonNingunPadrino = new javax.swing.JRadioButton();
        jRadioButtonDosPadrinos = new javax.swing.JRadioButton();
        jRadioButtonCuatroPadrinos = new javax.swing.JRadioButton();
        jLabelDegrade5 = new javax.swing.JLabel();
        jButtonSiguiente = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("TFL"), this, org.jdesktop.beansbinding.BeanProperty.create("title"));
        bindingGroup.addBinding(binding);

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogoUNLa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IconUNLa30x30.png"))); // NOI18N
        jLabelLogoUNLa.setText("jLabel1");
        getContentPane().add(jLabelLogoUNLa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabelTitulo.setFont(new java.awt.Font("Calibri", 2, 16)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("DETERMINADOR DE SANCIONES PARA DELITOS CONTRA LAS PERSONAS, EL HONOR Y LA INTEGRIDAD SEXUAL");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 17, 720, 20));

        jLabelSituacion.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelSituacion.setText("Indique la situación sucedida:");
        getContentPane().add(jLabelSituacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 20));

        jLabelDegrade1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDegrade1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade1.png"))); // NOI18N
        getContentPane().add(jLabelDegrade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 840, 40));

        jComboBoxSituaciones.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxSituaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la situación sucedida", "Batirse a duelo (Condiciones puestas por combatientes)", "Batirse a duelo (Condiciones puestas por padrinos)", "Participar de un duelo como padrino", "Instigar a otro a provocar o a aceptar un duelo", "Desacreditar públicamente a otro por no desafiar o por rehusar un desafío", "Provocar o dar causa a un desafío, proponiéndose un interés pecunario u otro objeto inmoral", "Padrinos de un duelo utilizan cualquier género de alevosía en la ejecución del mismo", "Padrinos conciertan un duelo a muerte o en condiciones tales que de ellas debiere resultar la muerte" }));
        jComboBoxSituaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSituacionesActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxSituaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabelDegrade2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        jLabelDegrade2.setText("jLabel1");
        getContentPane().add(jLabelDegrade2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 780, 50));

        jLabelCircExt.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelCircExt.setText("¿Se concretó el duelo?");
        getContentPane().add(jLabelCircExt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 20));

        jLabelCantidadVictimarios.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelCantidadVictimarios.setText("¿Cuántos padrinos hubo?");
        getContentPane().add(jLabelCantidadVictimarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, 20));

        jLabelDegrade3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDegrade3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade1.png"))); // NOI18N
        getContentPane().add(jLabelDegrade3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 840, 40));

        buttonGroup1.add(jRadioButtonSi);
        jRadioButtonSi.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButtonSi.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonSi.setText("Si");
        jRadioButtonSi.setContentAreaFilled(false);
        jRadioButtonSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSiActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 60, -1));

        buttonGroup1.add(jRadioButtonNo);
        jRadioButtonNo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButtonNo.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonNo.setText("No");
        jRadioButtonNo.setContentAreaFilled(false);
        jRadioButtonNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNoActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 60, -1));

        jLabelDegrade4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        jLabelDegrade4.setText("jLabel1");
        getContentPane().add(jLabelDegrade4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 120, 30));

        jTextFieldNombreApellido.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldNombreApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreApellidoActionPerformed(evt);
            }
        });
        jTextFieldNombreApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreApellidoKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldNombreApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 270, 30));

        jTextFieldDNI.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDNIActionPerformed(evt);
            }
        });
        jTextFieldDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDNIKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 100, 30));

        jTextFieldEdad.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEdadActionPerformed(evt);
            }
        });
        jTextFieldEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEdadKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 90, 30));

        jLabelDatosVictimario.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDatosVictimario.setText("Ingrese los datos del victimario:");
        getContentPane().add(jLabelDatosVictimario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, 20));

        jLabelEdad.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEdad.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelEdad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdad.setText("Edad:");
        getContentPane().add(jLabelEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, -1, -1));

        jButtonConfirmarDatos.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jButtonConfirmarDatos.setText("Confirmar datos");
        jButtonConfirmarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarDatosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirmarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 170, 50));

        jLabelDNI.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDNI.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelDNI.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDNI.setText("DNI:");
        getContentPane().add(jLabelDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, -1, -1));

        jLabelNombreApellido.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNombreApellido.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelNombreApellido.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreApellido.setText("Nombre y apellido:");
        getContentPane().add(jLabelNombreApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        jLabelDegrade7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        jLabelDegrade7.setText("jLabel1");
        getContentPane().add(jLabelDegrade7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 540, 110));

        jLabelRelacionConVictima.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelRelacionConVictima.setText("Seleccione la relación del victimario con alguna de las víctimas:");
        getContentPane().add(jLabelRelacionConVictima, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, 20));

        buttonGroup2.add(jRadioButtonOtra);
        jRadioButtonOtra.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButtonOtra.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonOtra.setText("Otra");
        jRadioButtonOtra.setContentAreaFilled(false);
        jRadioButtonOtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOtraActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonOtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 560, 70, -1));

        buttonGroup2.add(jRadioButtonParejaExPareja);
        jRadioButtonParejaExPareja.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButtonParejaExPareja.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonParejaExPareja.setText("Pareja/Ex pareja");
        jRadioButtonParejaExPareja.setContentAreaFilled(false);
        jRadioButtonParejaExPareja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonParejaExParejaActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonParejaExPareja, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 560, 150, -1));

        buttonGroup2.add(jRadioButtonConyugeExConyuge);
        jRadioButtonConyugeExConyuge.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButtonConyugeExConyuge.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonConyugeExConyuge.setText("Cónyuge/Ex cónyuge");
        jRadioButtonConyugeExConyuge.setContentAreaFilled(false);
        jRadioButtonConyugeExConyuge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonConyugeExConyugeActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonConyugeExConyuge, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 560, 190, -1));

        buttonGroup2.add(jRadioButtonAscendenteDescendente);
        jRadioButtonAscendenteDescendente.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButtonAscendenteDescendente.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonAscendenteDescendente.setText("Ascendente/Descendente");
        jRadioButtonAscendenteDescendente.setContentAreaFilled(false);
        jRadioButtonAscendenteDescendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAscendenteDescendenteActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonAscendenteDescendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 220, -1));

        jLabelDegrade6.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDegrade6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade1.png"))); // NOI18N
        getContentPane().add(jLabelDegrade6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 840, 40));

        jLabelDegrade8.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDegrade8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade1.png"))); // NOI18N
        getContentPane().add(jLabelDegrade8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 840, 40));

        jLabelDegrade9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        jLabelDegrade9.setText("jLabel1");
        getContentPane().add(jLabelDegrade9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 650, 30));

        buttonGroup3.add(jRadioButtonNingunPadrino);
        jRadioButtonNingunPadrino.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButtonNingunPadrino.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonNingunPadrino.setText("Cero");
        jRadioButtonNingunPadrino.setContentAreaFilled(false);
        jRadioButtonNingunPadrino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNingunPadrinoActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonNingunPadrino, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 70, -1));

        buttonGroup3.add(jRadioButtonDosPadrinos);
        jRadioButtonDosPadrinos.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButtonDosPadrinos.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonDosPadrinos.setText("Dos");
        jRadioButtonDosPadrinos.setContentAreaFilled(false);
        jRadioButtonDosPadrinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDosPadrinosActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonDosPadrinos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 60, -1));

        buttonGroup3.add(jRadioButtonCuatroPadrinos);
        jRadioButtonCuatroPadrinos.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButtonCuatroPadrinos.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonCuatroPadrinos.setText("Cuatro");
        jRadioButtonCuatroPadrinos.setContentAreaFilled(false);
        jRadioButtonCuatroPadrinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCuatroPadrinosActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonCuatroPadrinos, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 80, -1));

        jLabelDegrade5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        jLabelDegrade5.setText("jLabel1");
        getContentPane().add(jLabelDegrade5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 230, 30));

        jButtonSiguiente.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jButtonSiguiente.setText("Siguiente");
        jButtonSiguiente.setEnabled(false);
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 660, 150, 50));

        jLabelFondo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 740));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mostrarCircExt (boolean mostrar) {
        jLabelDegrade3.setVisible(mostrar);
        jLabelCircExt.setVisible(mostrar);
        jLabelDegrade4.setVisible(mostrar);
        jRadioButtonSi.setVisible(mostrar);
        jRadioButtonNo.setVisible(mostrar);
    }

    public void mostrarCantidadVictimarios (boolean mostrar) {
        jLabelCantidadVictimarios.setVisible(mostrar);
        jLabelDegrade5.setVisible(mostrar);
        jRadioButtonNingunPadrino.setVisible(mostrar);
        jRadioButtonDosPadrinos.setVisible(mostrar);
        jRadioButtonCuatroPadrinos.setVisible(mostrar);
    }

    public void mostrarDatosVictimario (boolean mostrar) {
        jLabelDegrade6.setVisible(mostrar);
        jLabelDatosVictimario.setVisible(mostrar);
        jLabelDegrade7.setVisible(mostrar);
        jLabelNombreApellido.setVisible(mostrar);
        jTextFieldNombreApellido.setVisible(mostrar);
        jLabelDNI.setVisible(mostrar);
        jTextFieldDNI.setVisible(mostrar);
        jLabelEdad.setVisible(mostrar);
        jTextFieldEdad.setVisible(mostrar);
        jButtonConfirmarDatos.setVisible(mostrar);
    }
    
    public void mostrarRelacion (boolean mostrar) {
        jLabelDegrade8.setVisible(mostrar);
        jLabelRelacionConVictima.setVisible(mostrar);
        jLabelDegrade9.setVisible(mostrar);
        jRadioButtonAscendenteDescendente.setVisible(mostrar);
        jRadioButtonConyugeExConyuge.setVisible(mostrar);
        jRadioButtonParejaExPareja.setVisible(mostrar);
        jRadioButtonOtra.setVisible(mostrar);
    }
    
    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        if (jRadioButtonNo.isSelected()){
            Condena a = new Condena();
            a.setVisible(true);
            this.setVisible(false);            
        }
        if (jRadioButtonSi.isSelected()){
            DueloVictima a = new DueloVictima();
            a.setVisible(true);
            this.setVisible(false);            
        }
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void jTextFieldNombreApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreApellidoActionPerformed

    }//GEN-LAST:event_jTextFieldNombreApellidoActionPerformed

    private void jRadioButtonOtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOtraActionPerformed
        if (jRadioButtonOtra.isSelected()) {
            jButtonSiguiente.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonOtraActionPerformed

    private void jRadioButtonParejaExParejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonParejaExParejaActionPerformed
        if (jRadioButtonParejaExPareja.isSelected()) {
            jButtonSiguiente.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonParejaExParejaActionPerformed

    private void jRadioButtonConyugeExConyugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonConyugeExConyugeActionPerformed
        if (jRadioButtonConyugeExConyuge.isSelected()) {
            jButtonSiguiente.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonConyugeExConyugeActionPerformed

    private void jRadioButtonAscendenteDescendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAscendenteDescendenteActionPerformed
        if (jRadioButtonAscendenteDescendente.isSelected()) {
            jButtonSiguiente.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonAscendenteDescendenteActionPerformed

    private void jRadioButtonNingunPadrinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNingunPadrinoActionPerformed
        if (jRadioButtonNingunPadrino.isSelected()) {
            if (jTextFieldNombreApellido.isEnabled() == true) {
                mostrarDatosVictimario(true);                
            }
        }
    }//GEN-LAST:event_jRadioButtonNingunPadrinoActionPerformed

    private void jRadioButtonDosPadrinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDosPadrinosActionPerformed
        if (jRadioButtonDosPadrinos.isSelected()) {
            if (jTextFieldNombreApellido.isEnabled() == true) {
                mostrarDatosVictimario(true);                
            }
        }
    }//GEN-LAST:event_jRadioButtonDosPadrinosActionPerformed

    private void jRadioButtonCuatroPadrinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCuatroPadrinosActionPerformed
        if (jRadioButtonCuatroPadrinos.isSelected()) {
            if (jTextFieldNombreApellido.isEnabled() == true) {
                mostrarDatosVictimario(true);                
            }
        }
    }//GEN-LAST:event_jRadioButtonCuatroPadrinosActionPerformed

    private void jTextFieldDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDNIKeyTyped
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_jTextFieldDNIKeyTyped

    private void jTextFieldEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEdadKeyTyped
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_jTextFieldEdadKeyTyped

    private void jTextFieldNombreApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreApellidoKeyTyped
//        char c = evt.getKeyChar();
//        if ((c<'a' || c>'z' ) && (c<'A' || c>'Z') && (c==' ')) evt.consume();
    }//GEN-LAST:event_jTextFieldNombreApellidoKeyTyped

    private void jTextFieldDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDNIActionPerformed

    }//GEN-LAST:event_jTextFieldDNIActionPerformed

    private void jButtonConfirmarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarDatosActionPerformed
        if ((!jTextFieldNombreApellido.getText().isEmpty()) && (!jTextFieldDNI.getText().isEmpty()) && (!jTextFieldEdad.getText().isEmpty())) {
            mostrarRelacion(true);
            jTextFieldNombreApellido.setEnabled(false);
            jTextFieldDNI.setEnabled(false);
            jTextFieldEdad.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonConfirmarDatosActionPerformed

    private void jTextFieldEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEdadActionPerformed

    private void jRadioButtonSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSiActionPerformed
        if (jRadioButtonSi.isSelected()) {
            jRadioButtonSi.setEnabled(false);
            jRadioButtonNo.setEnabled(false);
            jLabelCantidadVictimarios.setVisible(true);
            jLabelDegrade5.setVisible(true);

            if ((((String)jComboBoxSituaciones.getSelectedItem() == "Batirse a duelo (Condiciones puestas por combatientes)")) ||
                
                (((String)jComboBoxSituaciones.getSelectedItem() == "Instigar a otro a provocar o a aceptar un duelo")) ||
                (((String)jComboBoxSituaciones.getSelectedItem() == "Desacreditar públicamente a otro por no desafiar o por rehusar un desafío")) ||
                (((String)jComboBoxSituaciones.getSelectedItem() == "Provocar o dar causa a un desafío, proponiéndose un interés pecunario u otro objeto inmoral"))) { 
                jRadioButtonNingunPadrino.setVisible(true);
                jRadioButtonDosPadrinos.setVisible(true);
                jRadioButtonCuatroPadrinos.setVisible(true);
            }                

            if ((((String)jComboBoxSituaciones.getSelectedItem() == "Batirse a duelo (Condiciones puestas por padrinos)")) ||
                (((String)jComboBoxSituaciones.getSelectedItem() == "Participar de un duelo como padrino")) ||
                (((String)jComboBoxSituaciones.getSelectedItem() == "Padrinos de un duelo utilizan cualquier género de alevosía en la ejecución del mismo")) ||
                (((String)jComboBoxSituaciones.getSelectedItem() == "Padrinos conciertan un duelo a muerte o en condiciones tales que de ellas debiere resultar la muerte"))) { 
                jRadioButtonNingunPadrino.setVisible(true);
                jRadioButtonNingunPadrino.setEnabled(false);
                jRadioButtonDosPadrinos.setVisible(true);
                jRadioButtonCuatroPadrinos.setVisible(true);            
            }   
        }
    }//GEN-LAST:event_jRadioButtonSiActionPerformed

    private void jRadioButtonNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNoActionPerformed
        if (jRadioButtonNo.isSelected()) {
            jRadioButtonSi.setEnabled(false);
            jRadioButtonNo.setEnabled(false);
            mostrarDatosVictimario(true);
        }
    }//GEN-LAST:event_jRadioButtonNoActionPerformed

    private void jComboBoxSituacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSituacionesActionPerformed
        if (((String)jComboBoxSituaciones.getSelectedItem() != "Seleccione la situación sucedida")) {
            jComboBoxSituaciones.setEnabled(false);
            mostrarCircExt(true);
        }

    }//GEN-LAST:event_jComboBoxSituacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }
 
    public static String getSituacion() {
        String resultado = (String)jComboBoxSituaciones.getSelectedItem();
        switch (resultado) {    
            case "Desacreditar públicamente a otro por no desafiar o por rehusar un desafío":
                resultado = "Desacreditar publicamente a otro por no desafiar o por rehusar un desafio";
                break;                
            case "Provocar o dar causa a un desafío, proponiéndose un interés pecunario u otro objeto inmoral":
                resultado = "Provocar o dar causa a un desafio, proponiendose un interes pecunario u otro objeto inmoral";
                break;                
            case "Padrinos de un duelo utilizan cualquier género de alevosía en la ejecución del mismo":
                resultado = "Padrinos de un duelo utilizan cualquier genero de alevosia en la ejecucion del mismo";
                break;                
        }
        return resultado;
    }

    public static String getRol() {
        String resultado = (String)jComboBoxSituaciones.getSelectedItem();
        switch (resultado) {
            case "Batirse a duelo (Condiciones puestas por combatientes)":
                resultado = "Combatiente";
                break;
            case "Batirse a duelo (Condiciones puestas por padrinos)":
                resultado = "Combatiente";
                break; 
            case "Participar de un duelo como padrino":
                resultado = "Padrino";
                break; 
            case "Instigar a otro a provocar o a aceptar un duelo":
                resultado = "Instigador";
                break; 
            case "Desacreditar públicamente a otro por no desafiar o por rehusar un desafío":
                resultado = "Instigador";
                break; 
            case "Provocar o dar causa a un desafío, proponiéndose un interés pecunario u otro objeto inmoral":
                resultado = "Instigador";
                break; 
            case "Padrinos de un duelo utilizan cualquier género de alevosía en la ejecución del mismo":
                resultado = "Padrino";
                break; 
            case "Padrinos conciertan un duelo a muerte o en condiciones tales que de ellas debiere resultar la muerte":
                resultado = "Padrino";
                break;                 
        }
        return resultado;
    }
    
    public static String getCircunstanciasExternasDeAtenuacion() {
        String resultado = "";
        if (jRadioButtonSi.isSelected()) {
            resultado = "No";
        }
        if (jRadioButtonNo.isSelected()) {
            resultado = "Si";
        }
        return resultado;
    }
    
    public static int getCantidadVictimarios() {
        int resultado = 1;
//        if (jRadioButtonNingunPadrino.isSelected()) {
//            resultado = 1;
//        }
        if (jRadioButtonDosPadrinos.isSelected()) {
            resultado = 3;
        }
        if (jRadioButtonCuatroPadrinos.isSelected()) {
            resultado = 5;
        }
        return resultado;
    }

    public static String getNombreApellido() {
        return (String)jTextFieldNombreApellido.getText();
    }
    
    public static int getDNI() {
        return Integer.parseInt(jTextFieldDNI.getText());
    }
    
    public static int getEdad() {
        return Integer.parseInt(jTextFieldEdad.getText());
    }

    public static String getRelacionConVictima() {
        String resultado = "";
        if (jRadioButtonAscendenteDescendente.isSelected()) {
           resultado = "Ascendente o descendente"; 
        }
        if (jRadioButtonConyugeExConyuge.isSelected()) {
            resultado = "Conyuge o ex conyuge";
        }
        if (jRadioButtonParejaExPareja.isSelected()) {
            resultado = "Pareja o ex pareja";
        }
        if (jRadioButtonOtra.isSelected()) {
            resultado = "Otra";
        }
        return resultado;
    }    
    
    public static String getTipoDuelo() {
        return "Duelo";
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButtonConfirmarDatos;
    private javax.swing.JButton jButtonSiguiente;
    private static javax.swing.JComboBox<String> jComboBoxSituaciones;
    private javax.swing.JLabel jLabelCantidadVictimarios;
    private javax.swing.JLabel jLabelCircExt;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelDatosVictimario;
    private javax.swing.JLabel jLabelDegrade1;
    private javax.swing.JLabel jLabelDegrade2;
    private javax.swing.JLabel jLabelDegrade3;
    private javax.swing.JLabel jLabelDegrade4;
    private javax.swing.JLabel jLabelDegrade5;
    private javax.swing.JLabel jLabelDegrade6;
    private javax.swing.JLabel jLabelDegrade7;
    private javax.swing.JLabel jLabelDegrade8;
    private javax.swing.JLabel jLabelDegrade9;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLogoUNLa;
    private javax.swing.JLabel jLabelNombreApellido;
    private javax.swing.JLabel jLabelRelacionConVictima;
    private javax.swing.JLabel jLabelSituacion;
    private javax.swing.JLabel jLabelTitulo;
    private static javax.swing.JRadioButton jRadioButtonAscendenteDescendente;
    private static javax.swing.JRadioButton jRadioButtonConyugeExConyuge;
    private static javax.swing.JRadioButton jRadioButtonCuatroPadrinos;
    private static javax.swing.JRadioButton jRadioButtonDosPadrinos;
    private static javax.swing.JRadioButton jRadioButtonNingunPadrino;
    private static javax.swing.JRadioButton jRadioButtonNo;
    private static javax.swing.JRadioButton jRadioButtonOtra;
    private static javax.swing.JRadioButton jRadioButtonParejaExPareja;
    private static javax.swing.JRadioButton jRadioButtonSi;
    private static javax.swing.JTextField jTextFieldDNI;
    private static javax.swing.JTextField jTextFieldEdad;
    private static javax.swing.JTextField jTextFieldNombreApellido;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
