/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

public class HomicidioVictima extends javax.swing.JFrame {
    
    public HomicidioVictima () {
        initComponents();
        this.setLocationRelativeTo(null);  // Se ejecuta en el medio de la pantalla
        
        mostrarCantidadVictimas(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelDatosVictima = new javax.swing.JLabel();
        jLabelEdad = new javax.swing.JLabel();
        jLabelDegrade1 = new javax.swing.JLabel();
        jLabelLogoUNLa = new javax.swing.JLabel();
        jTextFieldNombreApellido = new javax.swing.JTextField();
        jTextFieldDNI = new javax.swing.JTextField();
        jTextFieldEdad = new javax.swing.JTextField();
        jLabelDNI = new javax.swing.JLabel();
        jLabelNombreApellido = new javax.swing.JLabel();
        jButtonSiguiente = new javax.swing.JButton();
        jLabelDegrade2 = new javax.swing.JLabel();
        jButtonConfirmarDatos1 = new javax.swing.JButton();
        jLabelCantidadVictimas1 = new javax.swing.JLabel();
        jLabelDegrade3 = new javax.swing.JLabel();
        jLabelCantidadVictimas2 = new javax.swing.JLabel();
        jTextFieldCantidadVictimas = new javax.swing.JTextField();
        jLabelDegrade4 = new javax.swing.JLabel();
        jButtonConfirmarDatos2 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("TFL"), this, org.jdesktop.beansbinding.BeanProperty.create("title"));
        bindingGroup.addBinding(binding);

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Calibri", 2, 16)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("DETERMINADOR DE SANCIONES PARA DELITOS CONTRA LAS PERSONAS, EL HONOR Y LA INTEGRIDAD SEXUAL");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 17, 720, 20));

        jLabelDatosVictima.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDatosVictima.setText("Ingrese los datos de la víctima:");
        getContentPane().add(jLabelDatosVictima, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 20));

        jLabelEdad.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEdad.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelEdad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdad.setText("Edad:");
        getContentPane().add(jLabelEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, -1));

        jLabelDegrade1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDegrade1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade1.png"))); // NOI18N
        getContentPane().add(jLabelDegrade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 840, 40));

        jLabelLogoUNLa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IconUNLa30x30.png"))); // NOI18N
        jLabelLogoUNLa.setText("jLabel1");
        getContentPane().add(jLabelLogoUNLa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jTextFieldNombreApellido.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldNombreApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreApellidoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombreApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 270, 30));

        jTextFieldDNI.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDNIActionPerformed(evt);
            }
        });
        jTextFieldDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDNIKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 100, 30));

        jTextFieldEdad.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEdadKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 90, 30));

        jLabelDNI.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDNI.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelDNI.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDNI.setText("DNI:");
        getContentPane().add(jLabelDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        jLabelNombreApellido.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNombreApellido.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelNombreApellido.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombreApellido.setText("Nombre y apellido:");
        getContentPane().add(jLabelNombreApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jButtonSiguiente.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jButtonSiguiente.setText("Siguiente");
        jButtonSiguiente.setEnabled(false);
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 660, 150, 50));

        jLabelDegrade2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        jLabelDegrade2.setText("jLabel1");
        getContentPane().add(jLabelDegrade2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 540, 110));

        jButtonConfirmarDatos1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jButtonConfirmarDatos1.setText("Confirmar datos");
        jButtonConfirmarDatos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarDatos1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirmarDatos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 170, 50));

        jLabelCantidadVictimas1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelCantidadVictimas1.setText("Indique la cantidad de víctimas:");
        getContentPane().add(jLabelCantidadVictimas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 20));

        jLabelDegrade3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDegrade3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade1.png"))); // NOI18N
        getContentPane().add(jLabelDegrade3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 840, 40));

        jLabelCantidadVictimas2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCantidadVictimas2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelCantidadVictimas2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCantidadVictimas2.setText("Cantidad de víctimas:");
        getContentPane().add(jLabelCantidadVictimas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jTextFieldCantidadVictimas.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldCantidadVictimas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCantidadVictimasKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldCantidadVictimas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 90, 30));

        jLabelDegrade4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        jLabelDegrade4.setText("jLabel1");
        getContentPane().add(jLabelDegrade4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 300, 70));

        jButtonConfirmarDatos2.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jButtonConfirmarDatos2.setText("Confirmar datos");
        jButtonConfirmarDatos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarDatos2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirmarDatos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 170, 50));

        jLabelFondo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 740));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mostrarCantidadVictimas (boolean mostrar) {
        jLabelDegrade3.setVisible(mostrar);
        jLabelCantidadVictimas1.setVisible(mostrar);
        jLabelDegrade4.setVisible(mostrar);
        jLabelCantidadVictimas2.setVisible(mostrar);
        jTextFieldCantidadVictimas.setVisible(mostrar);
        jButtonConfirmarDatos2.setVisible(mostrar);
    }
    
    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        Condena a = new Condena();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void jTextFieldNombreApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreApellidoActionPerformed

    private void jButtonConfirmarDatos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarDatos1ActionPerformed
        if ((!jTextFieldNombreApellido.getText().isEmpty()) && (!jTextFieldDNI.getText().isEmpty()) && (!jTextFieldEdad.getText().isEmpty())) {
            jButtonConfirmarDatos1.setVisible(false);
            mostrarCantidadVictimas(true);            
            jTextFieldNombreApellido.setEnabled(false);
            jTextFieldDNI.setEnabled(false);
            jTextFieldEdad.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonConfirmarDatos1ActionPerformed

    private void jTextFieldDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDNIActionPerformed

    private void jButtonConfirmarDatos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarDatos2ActionPerformed
        if ((!jTextFieldCantidadVictimas.getText().isEmpty())) {
            jTextFieldCantidadVictimas.setEnabled(false);
            jButtonConfirmarDatos2.setVisible(false);
            jButtonSiguiente.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonConfirmarDatos2ActionPerformed

    private void jTextFieldDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDNIKeyTyped
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_jTextFieldDNIKeyTyped

    private void jTextFieldEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEdadKeyTyped
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_jTextFieldEdadKeyTyped

    private void jTextFieldCantidadVictimasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCantidadVictimasKeyTyped
        char c = evt.getKeyChar();
        if (c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_jTextFieldCantidadVictimasKeyTyped

    
    public static String getNombreApellido() {
        return (String)jTextFieldNombreApellido.getText();
    }
    
    public static int getDNI() {
        return Integer.parseInt(jTextFieldDNI.getText());
    }
    
    public static int getEdad() {
        return Integer.parseInt(jTextFieldEdad.getText());
    }
    
    public static int getCantidadVictimas() {
        return Integer.parseInt(jTextFieldCantidadVictimas.getText());
    }   
    
    public static String getEstado() {
        return "Fallecido";
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonConfirmarDatos1;
    private javax.swing.JButton jButtonConfirmarDatos2;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JLabel jLabelCantidadVictimas1;
    private javax.swing.JLabel jLabelCantidadVictimas2;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelDatosVictima;
    private javax.swing.JLabel jLabelDegrade1;
    private javax.swing.JLabel jLabelDegrade2;
    private javax.swing.JLabel jLabelDegrade3;
    private javax.swing.JLabel jLabelDegrade4;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLogoUNLa;
    private javax.swing.JLabel jLabelNombreApellido;
    private javax.swing.JLabel jLabelTitulo;
    private static javax.swing.JTextField jTextFieldCantidadVictimas;
    private static javax.swing.JTextField jTextFieldDNI;
    private static javax.swing.JTextField jTextFieldEdad;
    private static javax.swing.JTextField jTextFieldNombreApellido;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
