/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

public class Index extends javax.swing.JFrame {

    public Index() {
        initComponents();
        this.setLocationRelativeTo(null);  // Se ejecuta en el medio de la pantalla
        
        mostrarDelitoContraLasPersonas(false);
        mostrarDelitoContraElHonor(false);
        mostrarDelitoContraLaIntegridadSexual(false);

        mostrarDelitoContraLaVida(false);
        mostrarLesion1(false);
        mostrarConsecuenciaLaboral1(false);
        mostrarAbusoDeArmas(false);
        mostrarRiña(false);
        mostrarArrepentimiento(false);
        mostrarFuncionarioPublico(false);
        mostrarConsentimiento(false);
        
        mostrarLesion2(false);
        mostrarConsecuenciaLaboral2(false);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabelLogoUNLa = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelTipoDelito = new javax.swing.JLabel();
        jLabelDegrade1 = new javax.swing.JLabel();
        jComboBoxTipoDelito = new javax.swing.JComboBox<>();
        jLabelDegrade2 = new javax.swing.JLabel();
        jLabelTipoDelitoContraLasPersonas = new javax.swing.JLabel();
        jLabelTipoDelitoContraElHonor = new javax.swing.JLabel();
        jLabelTipoDelitoContraLaIntegridadSexual = new javax.swing.JLabel();
        jLabelDegrade3 = new javax.swing.JLabel();
        jComboBoxDelitosContraLasPersonas = new javax.swing.JComboBox<>();
        jLabelDegrade4 = new javax.swing.JLabel();
        jComboBoxDelitosContraElHonor = new javax.swing.JComboBox<>();
        jLabelDegrade5 = new javax.swing.JLabel();
        jComboBoxDelitosContraLaIntegridadSexual = new javax.swing.JComboBox<>();
        jLabelDegrade6 = new javax.swing.JLabel();
        jLabelTipoDelitoContraLaVida = new javax.swing.JLabel();
        jLabelArrepentimiento = new javax.swing.JLabel();
        jLabelFuncionarioPublico = new javax.swing.JLabel();
        jLabelTipoLesion1 = new javax.swing.JLabel();
        jLabelRiña = new javax.swing.JLabel();
        jLabelAbusoDeArmas = new javax.swing.JLabel();
        jLabelConsentimiento = new javax.swing.JLabel();
        jLabelDegrade7 = new javax.swing.JLabel();
        jLabelViolacion1 = new javax.swing.JLabel();
        jLabelViolacion2 = new javax.swing.JLabel();
        jComboBoxConsentimiento = new javax.swing.JComboBox<>();
        jLabelDegrade8 = new javax.swing.JLabel();
        jComboBoxDelitosContraLaVida = new javax.swing.JComboBox<>();
        jComboBoxAbusoDeArmas = new javax.swing.JComboBox<>();
        jComboBoxRiña = new javax.swing.JComboBox<>();
        jLabelDegrade9 = new javax.swing.JLabel();
        jComboBoxTipoLesion1 = new javax.swing.JComboBox<>();
        jLabelDegrade11 = new javax.swing.JLabel();
        jRadioButtonSi = new javax.swing.JRadioButton();
        jRadioButtonNo = new javax.swing.JRadioButton();
        jComboBoxConsecuenciaLaboral1 = new javax.swing.JComboBox<>();
        jLabelDegrade12 = new javax.swing.JLabel();
        jLabelDegrade10 = new javax.swing.JLabel();
        jLabelTipoLesion2 = new javax.swing.JLabel();
        jLabelDegrade13 = new javax.swing.JLabel();
        jComboBoxTipoLesion2 = new javax.swing.JComboBox<>();
        jLabelDegrade14 = new javax.swing.JLabel();
        jButtonSiguiente = new javax.swing.JButton();
        jComboBoxConsecuenciaLaboral2 = new javax.swing.JComboBox<>();
        jLabelDegrade15 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();
        jLabelEnviar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("TFL"), this, org.jdesktop.beansbinding.BeanProperty.create("title"));
        bindingGroup.addBinding(binding);

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogoUNLa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IconUNLa30x30.png"))); // NOI18N
        jLabelLogoUNLa.setText("jLabel1");
        getContentPane().add(jLabelLogoUNLa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabelTitulo.setFont(new java.awt.Font("Calibri", 2, 16)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("DETERMINADOR DE SANCIONES PARA DELITOS CONTRA LAS PERSONAS, EL HONOR Y LA INTEGRIDAD SEXUAL");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 17, 720, 20));

        jLabelTipoDelito.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelTipoDelito.setText("Indique el tipo de delito:");
        getContentPane().add(jLabelTipoDelito, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 20));

        jLabelDegrade1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDegrade1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade1.png"))); // NOI18N
        getContentPane().add(jLabelDegrade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 840, 40));

        jComboBoxTipoDelito.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxTipoDelito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el tipo de delito", "Delito contra las personas", "Delito contra el honor", "Delito contra la integridad sexual" }));
        jComboBoxTipoDelito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoDelitoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxTipoDelito, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 280, -1));

        jLabelDegrade2.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabelDegrade2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDegrade2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        getContentPane().add(jLabelDegrade2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 300, 50));

        jLabelTipoDelitoContraLasPersonas.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelTipoDelitoContraLasPersonas.setText("Indique el tipo de delito contra las personas:");
        getContentPane().add(jLabelTipoDelitoContraLasPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 20));

        jLabelTipoDelitoContraElHonor.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelTipoDelitoContraElHonor.setText("Indique el tipo de delito contra el honor:");
        getContentPane().add(jLabelTipoDelitoContraElHonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 20));

        jLabelTipoDelitoContraLaIntegridadSexual.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelTipoDelitoContraLaIntegridadSexual.setText("Indique el tipo de delito contra la integridad sexual:");
        getContentPane().add(jLabelTipoDelitoContraLaIntegridadSexual, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 20));

        jLabelDegrade3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDegrade3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade1.png"))); // NOI18N
        getContentPane().add(jLabelDegrade3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 840, 40));

        jComboBoxDelitosContraLasPersonas.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxDelitosContraLasPersonas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el tipo de delito contra las personas", "Delito contra la vida", "Lesión", "Homicidio o lesiones en riña", "Duelo", "Abuso de armas", "Abandono de persona" }));
        jComboBoxDelitosContraLasPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDelitosContraLasPersonasActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxDelitosContraLasPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 380, -1));

        jLabelDegrade4.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabelDegrade4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDegrade4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        getContentPane().add(jLabelDegrade4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 400, 50));

        jComboBoxDelitosContraElHonor.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxDelitosContraElHonor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el tipo de delito contra el honor", "Calumnia", "Injuria", "Acusado de injuria prueba la verdad de la imputación", "Publicar o reproducir injurias inferidas por otro, no siendo su contenido fiel a la fuente", "Publicar o reproducir calumnias inferidas por otro, no siendo su contenido fiel a la fuente", "Injuria realizada por defensores ante los tribunales y no dada a publicidad", "Injurias recíprocas", "Proporcionar información falsa contenida en un archivo de datos personales, sin generar perjuicio", "Proporcionar información falsa contenida en un archivo de datos personales, generando perjuicio" }));
        jComboBoxDelitosContraElHonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDelitosContraElHonorActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxDelitosContraElHonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 740, -1));

        jLabelDegrade5.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabelDegrade5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDegrade5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        getContentPane().add(jLabelDegrade5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 760, 50));

        jComboBoxDelitosContraLaIntegridadSexual.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxDelitosContraLaIntegridadSexual.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el tipo de delito contra la integridad sexual", "Abuso sexual", "Corrupción de menores", "Promoción o facilitación de prostitución / Proxenetismo agravado", "Rufianería", "Difusión de imágenes y espectáculos pornográficos de menores", "Exhibiciones obscenas", "Sustracción o retención de una persona con la intención de menoscabar su integridad sexual", "Grooming (Ciberacoso sexual infantil)" }));
        jComboBoxDelitosContraLaIntegridadSexual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDelitosContraLaIntegridadSexualActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxDelitosContraLaIntegridadSexual, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 700, -1));

        jLabelDegrade6.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabelDegrade6.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDegrade6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        getContentPane().add(jLabelDegrade6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 720, 50));

        jLabelTipoDelitoContraLaVida.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelTipoDelitoContraLaVida.setText("Indique el tipo de delito contra la vida:");
        getContentPane().add(jLabelTipoDelitoContraLaVida, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, 20));

        jLabelArrepentimiento.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelArrepentimiento.setText("¿Hubo arrepentimiento público por parte del acusado sobre la injuria o calumnia realizada?");
        getContentPane().add(jLabelArrepentimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, 20));

        jLabelFuncionarioPublico.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelFuncionarioPublico.setText("¿La información fue proporcionada por un funcionario público en ejercicio de sus funciones?");
        getContentPane().add(jLabelFuncionarioPublico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, 20));

        jLabelTipoLesion1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelTipoLesion1.setText("Indique la consecuencia que generó la lesión:");
        getContentPane().add(jLabelTipoLesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, 20));

        jLabelRiña.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelRiña.setText("Indique el delito cometido:");
        getContentPane().add(jLabelRiña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, 20));

        jLabelAbusoDeArmas.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelAbusoDeArmas.setText("Indique la situación sucedida:");
        getContentPane().add(jLabelAbusoDeArmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, 20));

        jLabelConsentimiento.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelConsentimiento.setText("¿Hubo consentimiento por parte de la victima?");
        getContentPane().add(jLabelConsentimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, 20));

        jLabelDegrade7.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDegrade7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade1.png"))); // NOI18N
        getContentPane().add(jLabelDegrade7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 840, 40));

        jLabelViolacion1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabelViolacion1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelViolacion1.setText("Si es menor de 13 años y hubo consentimiento,");
        getContentPane().add(jLabelViolacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 310, 30));

        jLabelViolacion2.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabelViolacion2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelViolacion2.setText("también se considera violación");
        getContentPane().add(jLabelViolacion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 220, 30));

        jComboBoxConsentimiento.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxConsentimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la situación sucedida", "Violación (Sin consentimiento de la víctima)", "Estupro (Con consentimiento de la víctima)" }));
        jComboBoxConsentimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxConsentimientoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxConsentimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 460, -1));

        jLabelDegrade8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        jLabelDegrade8.setText("jLabel1");
        getContentPane().add(jLabelDegrade8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 480, 50));

        jComboBoxDelitosContraLaVida.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxDelitosContraLaVida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el tipo de delito contra la vida", "Homicidio", "Instigar o ayudar a otro a cometer suicidio", "Aborto" }));
        jComboBoxDelitosContraLaVida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDelitosContraLaVidaActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxDelitosContraLaVida, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 350, -1));

        jComboBoxAbusoDeArmas.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxAbusoDeArmas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la situación sucedida", "Disparar arma de fuego", "Agresión con arma" }));
        jComboBoxAbusoDeArmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAbusoDeArmasActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxAbusoDeArmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 350, -1));

        jComboBoxRiña.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxRiña.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el delito cometido", "Homicidio en riña", "Lesión en riña" }));
        jComboBoxRiña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRiñaActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxRiña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 350, -1));

        jLabelDegrade9.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabelDegrade9.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDegrade9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        getContentPane().add(jLabelDegrade9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 370, 50));

        jComboBoxTipoLesion1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxTipoLesion1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el tipo de lesión", "Debilitación permanente de la salud", "Debilitación permanente de un sentido", "Debilitación permanente de un órgano", "Debilitación permanente de un miembro", "Dificultad permanente de la palabra", "Puesta en riesgo de la vida", "Deformación permanente en el rostro", "Enfermedad mental, cierta o probablemente incurable", "Enfermedad corporal, cierta o probablemente incurable", "Pérdida de un sentido", "Pérdida de un órgano", "Pérdida de un miembro", "Pérdida del uso de un órgano o miembro", "Pérdida de la palabra", "Pérdida de la capacidad de engendrar o concebir", "Daño en el cuerpo o en la salud", "Descripción por consecuencia laboral", "Otro daño no mencionado" }));
        jComboBoxTipoLesion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoLesion1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxTipoLesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 450, -1));

        jLabelDegrade11.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabelDegrade11.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDegrade11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        getContentPane().add(jLabelDegrade11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 470, 50));

        buttonGroup1.add(jRadioButtonSi);
        jRadioButtonSi.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButtonSi.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonSi.setText("Si");
        jRadioButtonSi.setContentAreaFilled(false);
        jRadioButtonSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSiActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 60, -1));

        buttonGroup1.add(jRadioButtonNo);
        jRadioButtonNo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButtonNo.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonNo.setText("No");
        jRadioButtonNo.setContentAreaFilled(false);
        jRadioButtonNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNoActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 60, -1));

        jComboBoxConsecuenciaLaboral1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxConsecuenciaLaboral1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la consecuencia laboral", "Inutilización laboral por más de un mes", "Inutilidad laboral permanente" }));
        jComboBoxConsecuenciaLaboral1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxConsecuenciaLaboral1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxConsecuenciaLaboral1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 340, -1));

        jLabelDegrade12.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabelDegrade12.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDegrade12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        getContentPane().add(jLabelDegrade12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 360, 50));

        jLabelDegrade10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        jLabelDegrade10.setText("jLabel1");
        getContentPane().add(jLabelDegrade10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 150, 60));

        jLabelTipoLesion2.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelTipoLesion2.setText("Indique la consecuencia que generó la lesión:");
        getContentPane().add(jLabelTipoLesion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, 20));

        jLabelDegrade13.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDegrade13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade1.png"))); // NOI18N
        getContentPane().add(jLabelDegrade13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 840, 40));

        jComboBoxTipoLesion2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxTipoLesion2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el tipo de lesión", "Debilitación permanente de la salud", "Debilitación permanente de un sentido", "Debilitación permanente de un órgano", "Debilitación permanente de un miembro", "Dificultad permanente de la palabra", "Puesta en riesgo de la vida", "Deformación permanente en el rostro", "Enfermedad mental, cierta o probablemente incurable", "Enfermedad corporal, cierta o probablemente incurable", "Pérdida de un sentido", "Pérdida de un órgano", "Pérdida de un miembro", "Pérdida del uso de un órgano o miembro", "Pérdida de la palabra", "Pérdida de la capacidad de engendrar o concebir", "Daño en el cuerpo o en la salud", "Descripción por consecuencia laboral", "Otro daño no mencionado" }));
        jComboBoxTipoLesion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoLesion2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxTipoLesion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 450, -1));

        jLabelDegrade14.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabelDegrade14.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDegrade14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        getContentPane().add(jLabelDegrade14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 470, 50));

        jButtonSiguiente.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jButtonSiguiente.setText("Siguiente");
        jButtonSiguiente.setEnabled(false);
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 660, 150, 50));

        jComboBoxConsecuenciaLaboral2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxConsecuenciaLaboral2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la consecuencia laboral", "Inutilización laboral por más de un mes", "Inutilidad laboral permanente" }));
        jComboBoxConsecuenciaLaboral2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxConsecuenciaLaboral2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxConsecuenciaLaboral2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 340, -1));

        jLabelDegrade15.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        jLabelDegrade15.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDegrade15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        getContentPane().add(jLabelDegrade15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 360, 50));

        jLabelFondo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 740));

        jLabelEnviar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabelEnviarPropertyChange(evt);
            }
        });
        getContentPane().add(jLabelEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, 100, 40));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mostrarDelitoContraLasPersonas(boolean mostrar) {
        jLabelDegrade3.setVisible(mostrar);
        jLabelTipoDelitoContraLasPersonas.setVisible(mostrar);
        jLabelDegrade4.setVisible(mostrar);
        jComboBoxDelitosContraLasPersonas.setVisible(mostrar);
    }
    
    public void mostrarDelitoContraElHonor(boolean mostrar) {
        jLabelDegrade3.setVisible(mostrar);
        jLabelTipoDelitoContraElHonor.setVisible(mostrar);
        jLabelDegrade5.setVisible(mostrar);
        jComboBoxDelitosContraElHonor.setVisible(mostrar);
    }
    
    public void mostrarDelitoContraLaIntegridadSexual(boolean mostrar) {
        jLabelDegrade3.setVisible(mostrar);
        jLabelTipoDelitoContraLaIntegridadSexual.setVisible(mostrar);
        jLabelDegrade6.setVisible(mostrar);
        jComboBoxDelitosContraLaIntegridadSexual.setVisible(mostrar);
    }

    public void mostrarDelitoContraLaVida(boolean mostrar) {
        jLabelDegrade7.setVisible(mostrar);
        jLabelTipoDelitoContraLaVida.setVisible(mostrar);
        jLabelDegrade9.setVisible(mostrar);
        jComboBoxDelitosContraLaVida.setVisible(mostrar);   
    }

    public void mostrarLesion1(boolean mostrar) {
        jLabelDegrade7.setVisible(mostrar);
        jLabelTipoLesion1.setVisible(mostrar);
        jLabelDegrade11.setVisible(mostrar);
        jComboBoxTipoLesion1.setVisible(mostrar);   
    }
    
    public void mostrarConsecuenciaLaboral1(boolean mostrar) {
        jLabelDegrade12.setVisible(mostrar);
        jComboBoxConsecuenciaLaboral1.setVisible(mostrar);    
    }

    public void mostrarAbusoDeArmas(boolean mostrar) {
        jLabelDegrade7.setVisible(mostrar);
        jLabelAbusoDeArmas.setVisible(mostrar);
        jLabelDegrade9.setVisible(mostrar);
        jComboBoxAbusoDeArmas.setVisible(mostrar);   
    }
    
    public void mostrarRiña(boolean mostrar) {
        jLabelDegrade7.setVisible(mostrar);
        jLabelRiña.setVisible(mostrar);
        jLabelDegrade9.setVisible(mostrar);
        jComboBoxRiña.setVisible(mostrar);   
    }    
    
    public void mostrarArrepentimiento(boolean mostrar) {
        jLabelDegrade7.setVisible(mostrar);
        jLabelArrepentimiento.setVisible(mostrar);
        jLabelDegrade10.setVisible(mostrar);
        jRadioButtonSi.setVisible(mostrar);
        jRadioButtonNo.setVisible(mostrar);
    }    
    
    public void mostrarFuncionarioPublico(boolean mostrar) {
        jLabelDegrade7.setVisible(mostrar);
        jLabelFuncionarioPublico.setVisible(mostrar);
        jLabelDegrade10.setVisible(mostrar);
        jRadioButtonSi.setVisible(mostrar);
        jRadioButtonNo.setVisible(mostrar);        
    }    
    
    public void mostrarConsentimiento(boolean mostrar) {
        jLabelConsentimiento.setVisible(mostrar);
        jLabelDegrade7.setVisible(mostrar);
        jLabelViolacion1.setVisible(mostrar);
        jLabelViolacion2.setVisible(mostrar);
        jComboBoxConsentimiento.setVisible(mostrar);
        jLabelDegrade8.setVisible(mostrar);
    }
    
    public void mostrarLesion2(boolean mostrar) {
        jLabelDegrade13.setVisible(mostrar);
        jLabelTipoLesion2.setVisible(mostrar);
        jLabelDegrade14.setVisible(mostrar);
        jComboBoxTipoLesion2.setVisible(mostrar);    
    } 
    
    public void mostrarConsecuenciaLaboral2(boolean mostrar) {
        jLabelDegrade15.setVisible(mostrar);
        jComboBoxConsecuenciaLaboral2.setVisible(mostrar);    
    } 

    public void mostrarBloques234(boolean mostrar) {
        mostrarDelitoContraLasPersonas(mostrar);
        mostrarDelitoContraElHonor(mostrar);
        mostrarDelitoContraLaIntegridadSexual(mostrar);
        mostrarDelitoContraLaVida(mostrar);
        mostrarLesion1(mostrar);
        mostrarConsecuenciaLaboral1(mostrar);
        mostrarAbusoDeArmas(mostrar);
        mostrarRiña(mostrar);
        mostrarArrepentimiento(mostrar);
        mostrarFuncionarioPublico(mostrar);
        mostrarConsentimiento(mostrar);
        mostrarLesion2(mostrar);    
        mostrarConsecuenciaLaboral2(mostrar);
    }
    
    public void mostrarBloques34(boolean mostrar) {
        mostrarDelitoContraLaVida(mostrar);
        mostrarLesion1(mostrar);
        mostrarConsecuenciaLaboral1(mostrar);
        mostrarAbusoDeArmas(mostrar);
        mostrarRiña(mostrar);
        mostrarArrepentimiento(mostrar);
        mostrarFuncionarioPublico(mostrar);
        mostrarConsentimiento(mostrar);
        mostrarLesion2(mostrar);
        mostrarConsecuenciaLaboral2(mostrar);
    }
    
    public void mostrarBloque4(boolean mostrar) {
        mostrarLesion2(mostrar);   
        mostrarConsecuenciaLaboral2(mostrar);
    }

    
    public void resetearBloque1() {
        jComboBoxTipoDelito.setSelectedItem("Seleccione el tipo de delito");
    }
    
    public void resetearBloques234() {
        jComboBoxDelitosContraLasPersonas.setSelectedItem("Seleccione el tipo de delito contra las personas");
        jComboBoxDelitosContraElHonor.setSelectedItem("Seleccione el tipo de delito contra el honor");
        jComboBoxDelitosContraLaIntegridadSexual.setSelectedItem("Seleccione el tipo de delito contra la integridad sexual");
        jComboBoxDelitosContraLaVida.setSelectedItem("Seleccione el tipo de delito contra la vida");
        jComboBoxTipoLesion1.setSelectedItem("Seleccion el tipo de lesion");
        jComboBoxConsecuenciaLaboral1.setSelectedItem("Seleccione la consecuencia laboral");
        jComboBoxAbusoDeArmas.setSelectedItem("Seleccione la situación sucedida");
        jComboBoxRiña.setSelectedItem("Seleccione el delito cometido");
        jComboBoxConsentimiento.setSelectedItem("Seleccione la situación sucedida");
        jComboBoxTipoLesion2.setSelectedItem("Seleccion el tipo de lesion");
        jComboBoxConsecuenciaLaboral2.setSelectedItem("Seleccione la consecuencia laboral");
    }
            
    public void resetearBloques34() {
        jComboBoxDelitosContraLaVida.setSelectedItem("Seleccione el tipo de delito contra la vida");
        jComboBoxTipoLesion1.setSelectedItem("Seleccione el tipo de lesión");
        jComboBoxConsecuenciaLaboral1.setSelectedItem("Seleccione la consecuencia laboral");
        jComboBoxAbusoDeArmas.setSelectedItem("Seleccione la situación sucedida");
        jComboBoxRiña.setSelectedItem("Seleccione el delito cometido");
        jComboBoxConsentimiento.setSelectedItem("Seleccione la situación sucedida");
        jComboBoxTipoLesion2.setSelectedItem("Seleccione el tipo de lesión");
        jComboBoxConsecuenciaLaboral2.setSelectedItem("Seleccione la consecuencia laboral");
    }
    
    public void resetearBloque4() {
        jComboBoxTipoLesion2.setSelectedItem("Seleccione el tipo de lesión");
        jComboBoxConsecuenciaLaboral2.setSelectedItem("Seleccione la consecuencia laboral");
    }    
    
    public void resetearConsecuenciaLaboral() {
        jComboBoxConsecuenciaLaboral1.setSelectedItem("Seleccione la consecuencia laboral");
        jComboBoxConsecuenciaLaboral2.setSelectedItem("Seleccione la consecuencia laboral");
    }
    
    
    private void jComboBoxTipoDelitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoDelitoActionPerformed
        if ((String)jComboBoxTipoDelito.getSelectedItem() == "Seleccione el tipo de delito") {
            resetearBloques234();
            mostrarBloques234(false);
            jButtonSiguiente.setEnabled(false);            
        }
        if ((String)jComboBoxTipoDelito.getSelectedItem() == "Delito contra las personas") {
            resetearBloques234();
            mostrarBloques234(false);
            mostrarDelitoContraLasPersonas(true);
            jButtonSiguiente.setEnabled(false);            
        }
        if ((String)jComboBoxTipoDelito.getSelectedItem() == "Delito contra el honor") {
            resetearBloques234();
            mostrarBloques234(false);
            mostrarDelitoContraElHonor(true);
            jButtonSiguiente.setEnabled(false);            
        }
        if ((String)jComboBoxTipoDelito.getSelectedItem() == "Delito contra la integridad sexual") {
            resetearBloques234();
            mostrarBloques234(false);
            mostrarDelitoContraLaIntegridadSexual(true);
            jButtonSiguiente.setEnabled(false);            
        }        
    }//GEN-LAST:event_jComboBoxTipoDelitoActionPerformed

    private void jComboBoxDelitosContraLasPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDelitosContraLasPersonasActionPerformed
        if ((String)jComboBoxDelitosContraLasPersonas.getSelectedItem() == "Seleccione el tipo de delito contra las personas") {
            resetearBloques34();
            mostrarBloques34(false);
            if (jComboBoxTipoDelito.getSelectedItem() == "Delito contra las personas") {
                mostrarDelitoContraLasPersonas(true);                
            }
            jButtonSiguiente.setEnabled(false);
        }
        if ((String)jComboBoxDelitosContraLasPersonas.getSelectedItem() == "Delito contra la vida") {
            resetearBloques34();
            mostrarBloques34(false);
            mostrarDelitoContraLaVida(true);
            jButtonSiguiente.setEnabled(false);
        }
        if ((String)jComboBoxDelitosContraLasPersonas.getSelectedItem() == "Lesión") {
            resetearBloques34();
            mostrarBloques34(false);
            mostrarLesion1(true);
            jButtonSiguiente.setEnabled(false);
        }
        if ((String)jComboBoxDelitosContraLasPersonas.getSelectedItem() == "Homicidio o lesiones en riña") {
            resetearBloques34();
            mostrarBloques34(false);
            mostrarRiña(true);
            jButtonSiguiente.setEnabled(false);
        }  
        if ((String)jComboBoxDelitosContraLasPersonas.getSelectedItem() == "Duelo") {
            resetearBloques34();
            mostrarBloques34(false);
            jButtonSiguiente.setEnabled(true);
        }  
        if ((String)jComboBoxDelitosContraLasPersonas.getSelectedItem() == "Abuso de armas") {
            resetearBloques34();
            mostrarBloques34(false);
            mostrarAbusoDeArmas(true);
            jButtonSiguiente.setEnabled(false);
        }  
        if ((String)jComboBoxDelitosContraLasPersonas.getSelectedItem() == "Abandono de persona") {
            resetearBloques34();
            mostrarBloques34(false);
            jButtonSiguiente.setEnabled(true);
        }  
    }//GEN-LAST:event_jComboBoxDelitosContraLasPersonasActionPerformed

    private void jComboBoxDelitosContraElHonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDelitosContraElHonorActionPerformed
        if ((String)jComboBoxDelitosContraElHonor.getSelectedItem() == "Seleccione el tipo de delito contra el honor") {
            resetearBloques34();
            mostrarBloques34(false);
            if (jComboBoxTipoDelito.getSelectedItem() == "Delito contra el honor") {
                mostrarDelitoContraElHonor(true);                
            }
            jButtonSiguiente.setEnabled(false);
        }
        if (((String)jComboBoxDelitosContraElHonor.getSelectedItem() == "Acusado de injuria prueba la verdad de la imputación") ||
            ((String)jComboBoxDelitosContraElHonor.getSelectedItem() == "Injuria realizada por defensores ante los tribunales y no dada a publicidad") ||
            ((String)jComboBoxDelitosContraElHonor.getSelectedItem() == "Injurias recíprocas")) {
            resetearBloques34();
            mostrarBloques34(false);
            if (jComboBoxTipoDelito.getSelectedItem() == "Delito contra el honor") {
                mostrarDelitoContraElHonor(true);                
            }            
            jButtonSiguiente.setEnabled(true); 
        }
        if (((String)jComboBoxDelitosContraElHonor.getSelectedItem() == "Proporcionar información falsa contenida en un archivo de datos personales, sin generar perjuicio") ||
            ((String)jComboBoxDelitosContraElHonor.getSelectedItem() == "Proporcionar información falsa contenida en un archivo de datos personales, generando perjuicio")) {
            resetearBloques34();
            mostrarBloques34(false);
            mostrarFuncionarioPublico(true);
            jButtonSiguiente.setEnabled(false);
        }        
        if (((String)jComboBoxDelitosContraElHonor.getSelectedItem() == "Calumnia") ||
            ((String)jComboBoxDelitosContraElHonor.getSelectedItem() == "Injuria") ||
            ((String)jComboBoxDelitosContraElHonor.getSelectedItem() == "Publicar o reproducir injurias inferidas por otro, no siendo su contenido fiel a la fuente") ||
            ((String)jComboBoxDelitosContraElHonor.getSelectedItem() == "Publicar o reproducir calumnias inferidas por otro, no siendo su contenido fiel a la fuente")) {
            resetearBloques34();
            mostrarBloques34(false);
            mostrarArrepentimiento(true);
            jButtonSiguiente.setEnabled(false);
        }        
    }//GEN-LAST:event_jComboBoxDelitosContraElHonorActionPerformed

    private void jComboBoxDelitosContraLaIntegridadSexualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDelitosContraLaIntegridadSexualActionPerformed
        if ((String)jComboBoxDelitosContraLaIntegridadSexual.getSelectedItem() == "Seleccione el tipo de delito contra la integridad sexual") {
            resetearBloques34();
            mostrarBloques34(false);
            if (jComboBoxTipoDelito.getSelectedItem() == "Delito contra la integridad sexual") {
                mostrarDelitoContraLaIntegridadSexual(true);                
            }
            jButtonSiguiente.setEnabled(false);       
        }
        if (((String)jComboBoxDelitosContraLaIntegridadSexual.getSelectedItem() == "Abuso sexual")) {
            resetearBloques34();
            mostrarBloques34(false);
            mostrarConsentimiento(true);
            jButtonSiguiente.setEnabled(false);
        }
        if (((String)jComboBoxDelitosContraLaIntegridadSexual.getSelectedItem() != "Seleccione el tipo de delito contra la integridad sexual") &&
            ((String)jComboBoxDelitosContraLaIntegridadSexual.getSelectedItem() != "Abuso sexual")) {
            resetearBloques34();
            mostrarBloques34(false);
            mostrarConsentimiento(false);
            jButtonSiguiente.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBoxDelitosContraLaIntegridadSexualActionPerformed

    private void jComboBoxDelitosContraLaVidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDelitosContraLaVidaActionPerformed
        if ((String)jComboBoxDelitosContraLaVida.getSelectedItem() == "Seleccione el tipo de delito contra la vida") {
            jButtonSiguiente.setEnabled(false);
        }
        if ((String)jComboBoxDelitosContraLaVida.getSelectedItem() != "Seleccione el tipo de delito contra la vida") {
            jButtonSiguiente.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBoxDelitosContraLaVidaActionPerformed

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        if  (((String)jComboBoxDelitosContraLasPersonas.getSelectedItem() == "Delito contra la vida") && ((String)jComboBoxDelitosContraLaVida.getSelectedItem() == "Homicidio")) {
            HomicidioProcedimientoMotivoCircExt a = new HomicidioProcedimientoMotivoCircExt();
            a.setVisible(true);
            this.setVisible(false);
        }
        if  (((String)jComboBoxDelitosContraLasPersonas.getSelectedItem() == "Delito contra la vida") && ((String)jComboBoxDelitosContraLaVida.getSelectedItem() == "Instigar o ayudar a otro a cometer suicidio")) {
            SuicidioVictimario a = new SuicidioVictimario();
            a.setVisible(true);
            this.setVisible(false);
        }
        if  (((String)jComboBoxDelitosContraLasPersonas.getSelectedItem() == "Delito contra la vida") && ((String)jComboBoxDelitosContraLaVida.getSelectedItem() == "Aborto")) {
            AbortoProcedimientoMotivo a = new AbortoProcedimientoMotivo();
            a.setVisible(true);
            this.setVisible(false);
        }        
        if  (((String)jComboBoxDelitosContraLasPersonas.getSelectedItem() == "Lesión")) {
            LesionProcedimientoMotivoCircExt a = new LesionProcedimientoMotivoCircExt();
            a.setVisible(true);
            this.setVisible(false);
        }
        if  (((String)jComboBoxDelitosContraLasPersonas.getSelectedItem() == "Homicidio o lesiones en riña")) {
            RiñaVictimarioVictima a = new RiñaVictimarioVictima();
            a.setVisible(true);
            this.setVisible(false);
        }
        if  (((String)jComboBoxDelitosContraLasPersonas.getSelectedItem() == "Duelo")) {
            DueloSituacion a = new DueloSituacion();
            a.setVisible(true);
            this.setVisible(false);
        }
        if  (((String)jComboBoxDelitosContraLasPersonas.getSelectedItem() == "Abuso de armas")) {
            AbusoDeArmasVictimario a = new AbusoDeArmasVictimario();
            a.setVisible(true);
            this.setVisible(false);
        }
        if  (((String)jComboBoxDelitosContraLasPersonas.getSelectedItem() == "Abandono de persona")) {
            AbandonoProcedimientoCircExt a = new AbandonoProcedimientoCircExt();
            a.setVisible(true);
            this.setVisible(false);
        }
        if  (((String)jComboBoxTipoDelito.getSelectedItem() == "Delito contra el honor")) {
            DelitoContraElHonorVictimarioVictima a = new DelitoContraElHonorVictimarioVictima();
            a.setVisible(true);
            this.setVisible(false);
        }
        if (((String)jComboBoxDelitosContraLaIntegridadSexual.getSelectedItem() == "Abuso sexual")) {
            AbusoSexual a = new AbusoSexual();
            a.setVisible(true);
            this.setVisible(false);            
        }
        if (((String)jComboBoxDelitosContraLaIntegridadSexual.getSelectedItem() == "Corrupción de menores")) {
            CorrupcionDeMenores a = new CorrupcionDeMenores();
            a.setVisible(true);
            this.setVisible(false);            
        }
        if ((((String)jComboBoxDelitosContraLaIntegridadSexual.getSelectedItem() == "Promoción o facilitación de prostitución / Proxenetismo agravado"))
           || (((String)jComboBoxDelitosContraLaIntegridadSexual.getSelectedItem() == "Rufianería"))) {
            Prostitucion a = new Prostitucion();
            a.setVisible(true);
            this.setVisible(false);            
        }        
        if (((String)jComboBoxDelitosContraLaIntegridadSexual.getSelectedItem() == "Difusión de imágenes y espectáculos pornográficos de menores")) {
            DifusionDeImagenesYEspectaculosPornograficosDeMenores a = new DifusionDeImagenesYEspectaculosPornograficosDeMenores();
            a.setVisible(true);
            this.setVisible(false);            
        }
        if (((String)jComboBoxDelitosContraLaIntegridadSexual.getSelectedItem() == "Exhibiciones obscenas")) {
            ExhibicionesObscenas a = new ExhibicionesObscenas();
            a.setVisible(true);
            this.setVisible(false);            
        }
        if (((String)jComboBoxDelitosContraLaIntegridadSexual.getSelectedItem() == "Sustracción o retención de una persona con la intención de menoscabar su integridad sexual")) {
            SustraccionORetencionDeUnaPersona a = new SustraccionORetencionDeUnaPersona();
            a.setVisible(true);
            this.setVisible(false);            
        }
        if (((String)jComboBoxDelitosContraLaIntegridadSexual.getSelectedItem() == "Grooming (Ciberacoso sexual infantil)")) {
            Grooming a = new Grooming();
            a.setVisible(true);
            this.setVisible(false);            
        }        
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void jRadioButtonSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSiActionPerformed
        if (jRadioButtonSi.isSelected()) {
            jButtonSiguiente.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonSiActionPerformed

    private void jRadioButtonNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNoActionPerformed
        if (jRadioButtonNo.isSelected()) {
            jButtonSiguiente.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonNoActionPerformed

    private void jComboBoxTipoLesion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoLesion1ActionPerformed
        if  ((((String)jComboBoxTipoLesion1.getSelectedItem() != "Seleccione el tipo de lesión")) &&
            (((String)jComboBoxTipoLesion1.getSelectedItem() != "Descripción por consecuencia laboral"))) {
            jButtonSiguiente.setEnabled(true);
            mostrarConsecuenciaLaboral1(false);
        }
        if  (((String)jComboBoxTipoLesion1.getSelectedItem() == "Descripción por consecuencia laboral")) {
            mostrarConsecuenciaLaboral1(true);
            jButtonSiguiente.setEnabled(false);
            resetearConsecuenciaLaboral();
        }
        if  (((String)jComboBoxTipoLesion1.getSelectedItem() == "Seleccione el tipo de lesión")) {
            jButtonSiguiente.setEnabled(false);            
        }
    }//GEN-LAST:event_jComboBoxTipoLesion1ActionPerformed

    private void jComboBoxRiñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRiñaActionPerformed
        if  (((String)jComboBoxRiña.getSelectedItem() == "Seleccione el delito cometido")) {
            resetearBloque4();
            mostrarBloque4(false);
            jButtonSiguiente.setEnabled(false);
        }
        if  (((String)jComboBoxRiña.getSelectedItem() == "Homicidio en riña")) {
            resetearBloque4();
            mostrarBloque4(false);
            jButtonSiguiente.setEnabled(true);
        }   
        if  (((String)jComboBoxRiña.getSelectedItem() == "Lesión en riña")) {
            resetearBloque4();
            mostrarLesion2(true);
            jButtonSiguiente.setEnabled(false);
        }   
        
    }//GEN-LAST:event_jComboBoxRiñaActionPerformed

    private void jComboBoxTipoLesion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoLesion2ActionPerformed
        if  ((((String)jComboBoxTipoLesion2.getSelectedItem() != "Seleccione el tipo de lesión")) &&
            (((String)jComboBoxTipoLesion2.getSelectedItem() != "Descripción por consecuencia laboral"))) {
            jButtonSiguiente.setEnabled(true);
            mostrarConsecuenciaLaboral2(false);
        }
        if  (((String)jComboBoxTipoLesion2.getSelectedItem() == "Descripción por consecuencia laboral")) {
            mostrarConsecuenciaLaboral2(true);
            jButtonSiguiente.setEnabled(false);
            resetearConsecuenciaLaboral();
        }
        if  (((String)jComboBoxTipoLesion2.getSelectedItem() == "Seleccione el tipo de lesión")) {
            jButtonSiguiente.setEnabled(false);            
        }
    }//GEN-LAST:event_jComboBoxTipoLesion2ActionPerformed

    private void jComboBoxAbusoDeArmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAbusoDeArmasActionPerformed
       if  (((String)jComboBoxAbusoDeArmas.getSelectedItem() != "Seleccione la situación sucedida")) {
           jButtonSiguiente.setEnabled(false);
       }
        if  (((String)jComboBoxAbusoDeArmas.getSelectedItem() != "Seleccione la situación sucedida")) {
            jButtonSiguiente.setEnabled(true);
       }
    }//GEN-LAST:event_jComboBoxAbusoDeArmasActionPerformed

    private void jLabelEnviarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabelEnviarPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelEnviarPropertyChange

    private void jComboBoxConsentimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxConsentimientoActionPerformed
        if (((String)jComboBoxConsentimiento.getSelectedItem() == "Seleccione la situación sucedida")) {
            jButtonSiguiente.setEnabled(false);
        }
        if (((String)jComboBoxConsentimiento.getSelectedItem() != "Seleccione la situación sucedida")) {
            jButtonSiguiente.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBoxConsentimientoActionPerformed

    private void jComboBoxConsecuenciaLaboral2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxConsecuenciaLaboral2ActionPerformed
        if (((String)jComboBoxConsecuenciaLaboral2.getSelectedItem() != "Seleccione la consecuencia laboral")) {
            jButtonSiguiente.setEnabled(true);
        } 
        if (((String)jComboBoxConsecuenciaLaboral2.getSelectedItem() == "Seleccione la consecuencia laboral")) {
            jButtonSiguiente.setEnabled(false);
        } 
    }//GEN-LAST:event_jComboBoxConsecuenciaLaboral2ActionPerformed

    private void jComboBoxConsecuenciaLaboral1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxConsecuenciaLaboral1ActionPerformed
        if (((String)jComboBoxConsecuenciaLaboral1.getSelectedItem() != "Seleccione la consecuencia laboral")) {
            jButtonSiguiente.setEnabled(true);
        } 
        if (((String)jComboBoxConsecuenciaLaboral1.getSelectedItem() == "Seleccione la consecuencia laboral")) {
            jButtonSiguiente.setEnabled(false);
        }         
    }//GEN-LAST:event_jComboBoxConsecuenciaLaboral1ActionPerformed

    
    public static String getTipoDelito() {
        return (String)jComboBoxTipoDelito.getSelectedItem();
    }
    
    public static String getTipoDelitoContraLasPersonas() {
        String resultado = (String)jComboBoxDelitosContraLasPersonas.getSelectedItem();
        switch (resultado) {
            case "Lesión":
                resultado = "Lesion";
                break;
            case "Homicidio o lesiones en riña":
                resultado = "Homicidio o lesiones en rinia";
                break;
        }
        return resultado;
    }
            
    public static String getTipoDelitoContraElHonor() {
        String resultado = (String)jComboBoxDelitosContraElHonor.getSelectedItem();
        switch (resultado) {
            case "Calumnia":
                resultado = "Calumnia (Falsa imputacion a una persona fisica de la comision de un delito que de lugar a la accion publica)";
                break;
            case "Injuria":
                resultado = "Injuria (Deshonra o desacreditacion intencional a una persona fisica)";
                break;
            case "Acusado de injuria prueba la verdad de la imputación":
                resultado = "Ninguno (Acusado de injuria prueba la verdad de la imputacion)";
                break;
            case "Publicar o reproducir injurias inferidas por otro, no siendo su contenido fiel a la fuente":
                resultado = "Publicar o reproducir (en cualquier medio) injurias inferidas por otro, no siendo su contenido fiel a la fuente pertinente";
                break;
            case "Publicar o reproducir calumnias inferidas por otro, no siendo su contenido fiel a la fuente":
                resultado = "Publicar o reproducir (en cualquier medio) calumnias inferidas por otro, no siendo su contenido fiel a la fuente pertinente";
                break;
//            case "Injuria realizada por defensores ante los tribunales y no dada a publicidad":
//                resultado = "Injuria realizada por defensores ante los tribunales y no dada a publicidad";
//                break;
            case "Injurias recíprocas":
                resultado = "Injurias reciprocas";
                break;
            case "Proporcionar información falsa contenida en un archivo de datos personales, sin generar perjuicio":
                resultado = "Proporcionar a un tercero informacion falsa contenida en un archivo de datos personales, sin generar perjuicio a alguna persona";
                break;
            case "Proporcionar información falsa contenida en un archivo de datos personales, generando perjuicio":
                resultado = "Proporcionar a un tercero informacion falsa contenida en un archivo de datos personales, generando perjuicio a alguna persona";
                break;
        }
        return resultado;
    }
    
    public static String getTipoDelitoContraLaIntegridadSexual() {
        String resultado = (String)jComboBoxDelitosContraLaIntegridadSexual.getSelectedItem();
        switch (resultado) {
            case "Corrupción de menores":
                resultado = "Corrupcion de menores";
                break;
            case "Promoción o facilitación de prostitución / Proxenetismo agravado":
                resultado = "Promocion o facilitacion de prostitucion / Proxenetismo agravado";
                break;
            case "Rufianería":
                resultado = "Rufianeria";
                break;
            case "Difusión de imágenes y espectáculos pornográficos de menores":
                resultado = "Difusion de imagenes y espectaculos pornograficos de menores";
                break;
            case "Sustracción o retención de una persona con la intención de menoscabar su integridad sexual":
                resultado = "Sustraccion o retencion de una persona con la intencion de menoscabar su integridad sexual";
                break;
            case "Grooming (Ciberacoso sexual infantil)":
                resultado = "Grooming";
                break;                
        }
        return resultado;
    }

    public static String getTipoDelitoContraLaVida() {
        return (String)jComboBoxDelitosContraLaVida.getSelectedItem();
    }
    
    public static String getTipoLesion() {
        String resultado = "";
        if ((String)jComboBoxTipoLesion1.getSelectedItem() != "Seleccione el tipo de lesión") {
            resultado = (String)jComboBoxTipoLesion1.getSelectedItem();
        }
        if ((String)jComboBoxTipoLesion2.getSelectedItem() != "Seleccione el tipo de lesión") {
            resultado = (String)jComboBoxTipoLesion2.getSelectedItem();
        }        
        switch (resultado) {   
            case "Debilitación permanente de la salud":
                resultado = "Debilitacion permanente de la salud, de un sentido, de un organo, de un miembro o dificultad permanente de la palabra";
                break;                
            case "Debilitación permanente de un sentido":
                resultado = "Debilitacion permanente de la salud, de un sentido, de un organo, de un miembro o dificultad permanente de la palabra";
                break;                
            case "Debilitación permanente de un órgano":
                resultado = "Debilitacion permanente de la salud, de un sentido, de un organo, de un miembro o dificultad permanente de la palabra";
                break;                
            case "Debilitación permanente de un miembro":
                resultado = "Debilitacion permanente de la salud, de un sentido, de un organo, de un miembro o dificultad permanente de la palabra";
                break;                
            case "Dificultad permanente de la palabra":
                resultado = "Debilitacion permanente de la salud, de un sentido, de un organo, de un miembro o dificultad permanente de la palabra";
                break;   
            case "Enfermedad mental, cierta o probablemente incurable":
                resultado = "Enfermedad mental o corporal, cierta o probablemente incurable";
                break;  
            case "Enfermedad corporal, cierta o probablemente incurable":
                resultado = "Enfermedad mental o corporal, cierta o probablemente incurable";
                break;                  
        
            case "Descripción por consecuencia laboral":
                if ((String)jComboBoxTipoLesion1.getSelectedItem() != "Seleccione el tipo de lesión") {
                    if ((String)jComboBoxConsecuenciaLaboral1.getSelectedItem() == "Inutilización laboral por más de un mes") {
                        resultado = "Inutilizacion laboral por mas de un mes";
                    }
                    if ((String)jComboBoxConsecuenciaLaboral1.getSelectedItem() == "Inutilidad laboral permanente") {
                        resultado = "Inutilidad laboral permanente";
                    }                    
                }
                if ((String)jComboBoxTipoLesion2.getSelectedItem() != "Seleccione el tipo de lesión") {
                     if ((String)jComboBoxConsecuenciaLaboral2.getSelectedItem() == "Inutilización laboral por más de un mes") {
                        resultado = "Inutilizacion laboral por mas de un mes";
                    }
                    if ((String)jComboBoxConsecuenciaLaboral2.getSelectedItem() == "Inutilidad laboral permanente") {
                        resultado = "Inutilidad laboral permanente";
                    }                   
                }                
                break;                
            
            case "Deformación permanente en el rostro":
                resultado = "Deformacion permanente en el rostro";
                break;                

            case "Pérdida de un sentido":
                resultado = "Perdida de un sentido, de un organo, de un miembro, del uso de un organo o miembro, de la palabra o de la capacidad de engendrar o concebir";
                break;                
            case "Pérdida de un órgano":
                resultado = "Perdida de un sentido, de un organo, de un miembro, del uso de un organo o miembro, de la palabra o de la capacidad de engendrar o concebir";
                break;                
            case "Pérdida de un miembro":
                resultado = "Perdida de un sentido, de un organo, de un miembro, del uso de un organo o miembro, de la palabra o de la capacidad de engendrar o concebir";
                break;                
            case "Pérdida del uso de un órgano o miembro":
                resultado = "Perdida de un sentido, de un organo, de un miembro, del uso de un organo o miembro, de la palabra o de la capacidad de engendrar o concebir";
                break;                
            case "Pérdida de la palabra":
                resultado = "Perdida de un sentido, de un organo, de un miembro, del uso de un organo o miembro, de la palabra o de la capacidad de engendrar o concebir";
                break;                
            case "Pérdida de la capacidad de engendrar o concebir":
                resultado = "Perdida de un sentido, de un organo, de un miembro, del uso de un organo o miembro, de la palabra o de la capacidad de engendrar o concebir";
                break;                

            case "Daño en el cuerpo o en la salud":
                resultado = "Danio en el cuerpo o en la salud";
                break;                
            case "Otro daño no mencionado":
                resultado = "Otro danio no mencionado";
                break;     
                
        }
        return resultado;
    }
        
    public static String getTipoDelitoAbusoDeArmas() {
        String resultado = (String)jComboBoxAbusoDeArmas.getSelectedItem();
        switch (resultado) {    
            case "Agresión con arma":
                resultado = "Agresion con arma";
                break;                
        }
        return resultado;
    }

    public static String getTipoDelitoRiña() {
        String resultado = (String)jComboBoxRiña.getSelectedItem();
        switch (resultado) {    
            case "Homicidio en riña":
                resultado = "Homicidio en rinia";
                break;                
            case "Lesión en riña":
                resultado = "Lesion en rinia";
                break;                
        }
        return resultado;
    }
    
    public static String getCircunstanciasExternasDeAtenuacion() {
        String resultado = "";
        if (((String)jComboBoxDelitosContraElHonor.getSelectedItem() == "Calumnia")
            || ((String)jComboBoxDelitosContraElHonor.getSelectedItem() == "Injuria")
            || ((String)jComboBoxDelitosContraElHonor.getSelectedItem() == "Publicar o reproducir injurias inferidas por otro, no siendo su contenido fiel a la fuente")
            || ((String)jComboBoxDelitosContraElHonor.getSelectedItem() == "Publicar o reproducir calumnias inferidas por otro, no siendo su contenido fiel a la fuente")) {
            if (jRadioButtonSi.isSelected()) {
                resultado = "Si";
            }
            if (jRadioButtonNo.isSelected()) {
                resultado = "No";
            }        
        }
        if (((String)jComboBoxDelitosContraElHonor.getSelectedItem() == "Proporcionar información falsa contenida en un archivo de datos personales, sin generar perjuicio") 
            || ((String)jComboBoxDelitosContraElHonor.getSelectedItem() == "Proporcionar información falsa contenida en un archivo de datos personales, generando perjuicio")) {
            if (jRadioButtonSi.isSelected()) {
                resultado = "No";
            }
            if (jRadioButtonNo.isSelected()) {
                resultado = "Si";
            }
        }
        return resultado;
    }

    public static String getConsentimiento() {
        String resultado = (String)jComboBoxConsentimiento.getSelectedItem();
        switch (resultado) {    
            case "Violación (Sin consentimiento de la víctima)":
                resultado = "No";
                break;                
            case "Estupro (Con consentimiento de la víctima)":
                resultado = "Si";
                break;                
        }
        return resultado;
    }
    

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonSiguiente;
    private static javax.swing.JComboBox<String> jComboBoxAbusoDeArmas;
    private static javax.swing.JComboBox<String> jComboBoxConsecuenciaLaboral1;
    private static javax.swing.JComboBox<String> jComboBoxConsecuenciaLaboral2;
    private static javax.swing.JComboBox<String> jComboBoxConsentimiento;
    private static javax.swing.JComboBox<String> jComboBoxDelitosContraElHonor;
    private static javax.swing.JComboBox<String> jComboBoxDelitosContraLaIntegridadSexual;
    private static javax.swing.JComboBox<String> jComboBoxDelitosContraLaVida;
    private static javax.swing.JComboBox<String> jComboBoxDelitosContraLasPersonas;
    private static javax.swing.JComboBox<String> jComboBoxRiña;
    private static javax.swing.JComboBox<String> jComboBoxTipoDelito;
    private static javax.swing.JComboBox<String> jComboBoxTipoLesion1;
    private static javax.swing.JComboBox<String> jComboBoxTipoLesion2;
    private javax.swing.JLabel jLabelAbusoDeArmas;
    private javax.swing.JLabel jLabelArrepentimiento;
    private javax.swing.JLabel jLabelConsentimiento;
    private javax.swing.JLabel jLabelDegrade1;
    private javax.swing.JLabel jLabelDegrade10;
    private javax.swing.JLabel jLabelDegrade11;
    private javax.swing.JLabel jLabelDegrade12;
    private javax.swing.JLabel jLabelDegrade13;
    private javax.swing.JLabel jLabelDegrade14;
    private javax.swing.JLabel jLabelDegrade15;
    private javax.swing.JLabel jLabelDegrade2;
    private javax.swing.JLabel jLabelDegrade3;
    private javax.swing.JLabel jLabelDegrade4;
    private javax.swing.JLabel jLabelDegrade5;
    private javax.swing.JLabel jLabelDegrade6;
    private javax.swing.JLabel jLabelDegrade7;
    private javax.swing.JLabel jLabelDegrade8;
    private javax.swing.JLabel jLabelDegrade9;
    public static javax.swing.JLabel jLabelEnviar;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelFuncionarioPublico;
    private javax.swing.JLabel jLabelLogoUNLa;
    private javax.swing.JLabel jLabelRiña;
    private javax.swing.JLabel jLabelTipoDelito;
    private static javax.swing.JLabel jLabelTipoDelitoContraElHonor;
    private static javax.swing.JLabel jLabelTipoDelitoContraLaIntegridadSexual;
    private javax.swing.JLabel jLabelTipoDelitoContraLaVida;
    private static javax.swing.JLabel jLabelTipoDelitoContraLasPersonas;
    private javax.swing.JLabel jLabelTipoLesion1;
    private javax.swing.JLabel jLabelTipoLesion2;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelViolacion1;
    private javax.swing.JLabel jLabelViolacion2;
    private static javax.swing.JRadioButton jRadioButtonNo;
    private static javax.swing.JRadioButton jRadioButtonSi;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
