/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

public class LesionProcedimientoMotivoCircExt extends javax.swing.JFrame {

    public LesionProcedimientoMotivoCircExt () {
        initComponents();
        this.setLocationRelativeTo(null);  // Se ejecuta en el medio de la pantalla
        
        mostrarMotivos(false);
        mostrarCircExt1(false);
        mostrarCircExt2(false);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelProcedimiento = new javax.swing.JLabel();
        jLabelDegrade1 = new javax.swing.JLabel();
        jLabelLogoUNLa = new javax.swing.JLabel();
        jComboBoxProcedimientos = new javax.swing.JComboBox<>();
        jLabelDegrade2 = new javax.swing.JLabel();
        jLabelMotivo = new javax.swing.JLabel();
        jLabelConduccionCircExt = new javax.swing.JLabel();
        jLabelDegrade3 = new javax.swing.JLabel();
        jButtonSiguiente = new javax.swing.JButton();
        jComboBoxMotivos = new javax.swing.JComboBox<>();
        jLabelDegrade4 = new javax.swing.JLabel();
        jLabelCircExt = new javax.swing.JLabel();
        jLabelDegrade5 = new javax.swing.JLabel();
        jRadioButtonSi1 = new javax.swing.JRadioButton();
        jRadioButtonNo1 = new javax.swing.JRadioButton();
        jLabelDegrade6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonSi2 = new javax.swing.JRadioButton();
        jRadioButtonNo2 = new javax.swing.JRadioButton();
        jLabelDegrade8 = new javax.swing.JLabel();
        jLabelDegrade7 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(850, 700));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("TFL"), this, org.jdesktop.beansbinding.BeanProperty.create("title"));
        bindingGroup.addBinding(binding);

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Calibri", 2, 16)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("DETERMINADOR DE SANCIONES PARA DELITOS CONTRA LAS PERSONAS, EL HONOR Y LA INTEGRIDAD SEXUAL");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 17, 720, 20));

        jLabelProcedimiento.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelProcedimiento.setText("Indique el procedimiento mediante el cual se realizó el delito:");
        getContentPane().add(jLabelProcedimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 20));

        jLabelDegrade1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDegrade1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade1.png"))); // NOI18N
        getContentPane().add(jLabelDegrade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 840, 40));

        jLabelLogoUNLa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IconUNLa30x30.png"))); // NOI18N
        jLabelLogoUNLa.setText("jLabel1");
        getContentPane().add(jLabelLogoUNLa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jComboBoxProcedimientos.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxProcedimientos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el procedimiento", "Ningún procedimiento insidioso", "Ensañamiento", "Alevosía", "Veneno", "Emoción violenta", "Medio empleado no debería causar la muerte", "Imprudencia, negligencia o impericia en arte o profesión", "Inobservancia de reglamentos o deberes a cargo", "Conducción imprudente, negligente o antirreglamentaria de un vehículo con motor", "Otro procedimiento insidioso" }));
        jComboBoxProcedimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProcedimientosActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxProcedimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabelDegrade2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        jLabelDegrade2.setText("jLabel1");
        getContentPane().add(jLabelDegrade2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 660, 50));

        jLabelMotivo.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelMotivo.setText("Indique el motivo por el cual se cometió el delito:");
        getContentPane().add(jLabelMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 20));

        jLabelConduccionCircExt.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelConduccionCircExt.setText("¿Ocurrió alguna de las siguientes circunstancias?");
        getContentPane().add(jLabelConduccionCircExt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 20));

        jLabelDegrade3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDegrade3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade1.png"))); // NOI18N
        getContentPane().add(jLabelDegrade3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 840, 40));

        jButtonSiguiente.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jButtonSiguiente.setText("Siguiente");
        jButtonSiguiente.setEnabled(false);
        jButtonSiguiente.setMaximumSize(new java.awt.Dimension(39, 29));
        jButtonSiguiente.setMinimumSize(new java.awt.Dimension(39, 29));
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 660, 150, 50));

        jComboBoxMotivos.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxMotivos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el motivo", "Precio", "Promesa remuneratoria", "Placer", "Codicia", "Odio racial", "Odio religioso", "Odio de género", "Odio a la orientación sexual", "Odio a la identidad de género o su expresión", "Medio idóneo para crear un peligro común", "Función/cargo/condición de seguridad pública/policial/penitenciaria (de la víctima)", "Abuso de función/cargo de seguridad pública/policial/penitenciaria (del victimario)", "Violencia de género (De hombre a mujer)", "Causar sufrimiento", "Preparar otro delito", "Facilitar otro delito", "Consumar otro delito", "Ocultar otro delito", "Asegurar resultados de otro delito", "Procurar impunidad para sí u otro delito", "No haber logrado el fin de otro delito", "Causar daño en el cuerpo", "Ninguno de los anteriores" }));
        jComboBoxMotivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMotivosActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxMotivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabelDegrade4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        jLabelDegrade4.setText("jLabel1");
        getContentPane().add(jLabelDegrade4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 660, 50));

        jLabelCircExt.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelCircExt.setText("¿Hay circunstancias externas de atenuación?");
        getContentPane().add(jLabelCircExt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, 20));

        jLabelDegrade5.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabelDegrade5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade1.png"))); // NOI18N
        getContentPane().add(jLabelDegrade5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 840, 40));

        buttonGroup1.add(jRadioButtonSi1);
        jRadioButtonSi1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButtonSi1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonSi1.setText("Si");
        jRadioButtonSi1.setContentAreaFilled(false);
        jRadioButtonSi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSi1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonSi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 60, -1));

        buttonGroup1.add(jRadioButtonNo1);
        jRadioButtonNo1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButtonNo1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonNo1.setText("No");
        jRadioButtonNo1.setContentAreaFilled(false);
        jRadioButtonNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNo1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 60, -1));

        jLabelDegrade6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        jLabelDegrade6.setText("jLabel1");
        getContentPane().add(jLabelDegrade6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 150, 60));

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Conductor violó las señales de tránsito");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 300, 30));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Conductor violó señalizacion del semáforo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 330, 30));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Conductor condujo estando inhabilitado para hacerlo por autoridad competente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 590, 30));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Conductor condujo en exceso de velocidad de mas de 30 km por encima de la máxima permitida");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 710, 30));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Conductor superó los límites permitidos de alcohol en sangre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 450, 30));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Conductor condujo bajo efecto de estupefacientes");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 390, 30));

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Conductor no intentó socorrer a la victima");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 330, 30));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Conductor se fugó");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 250, 30));

        buttonGroup2.add(jRadioButtonSi2);
        jRadioButtonSi2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButtonSi2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonSi2.setText("Si");
        jRadioButtonSi2.setContentAreaFilled(false);
        jRadioButtonSi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSi2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonSi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, 60, -1));

        buttonGroup2.add(jRadioButtonNo2);
        jRadioButtonNo2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButtonNo2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonNo2.setText("No");
        jRadioButtonNo2.setContentAreaFilled(false);
        jRadioButtonNo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNo2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonNo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 60, -1));

        jLabelDegrade8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        jLabelDegrade8.setText("jLabel1");
        getContentPane().add(jLabelDegrade8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 150, 60));

        jLabelDegrade7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Degrade2.jpg"))); // NOI18N
        jLabelDegrade7.setText("jLabel1");
        getContentPane().add(jLabelDegrade7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 720, 330));

        jLabelFondo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 740));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarMotivos(boolean mostrar) {
        jLabelDegrade3.setVisible(mostrar);
        jLabelDegrade4.setVisible(mostrar);
        jLabelMotivo.setVisible(mostrar);
        jComboBoxMotivos.setVisible(mostrar);
    }

    private void mostrarCircExt1(boolean mostrar) {
        jLabelDegrade5.setVisible(mostrar);
        jLabelCircExt.setVisible(mostrar);
        jLabelDegrade6.setVisible(mostrar);
        jRadioButtonSi1.setVisible(mostrar);
        jRadioButtonNo1.setVisible(mostrar);
    }

    private void mostrarCircExt2(boolean mostrar) {
        jLabelDegrade3.setVisible(mostrar);
        jLabelDegrade7.setVisible(mostrar);
        jLabelConduccionCircExt.setVisible(mostrar);
        jLabel1.setVisible(mostrar);
        jLabel1.setVisible(mostrar);
        jLabel2.setVisible(mostrar);
        jLabel3.setVisible(mostrar);
        jLabel4.setVisible(mostrar);
        jLabel5.setVisible(mostrar);
        jLabel6.setVisible(mostrar);
        jLabel7.setVisible(mostrar);
        jLabel8.setVisible(mostrar);
        jRadioButtonSi2.setVisible(mostrar);
        jRadioButtonNo2.setVisible(mostrar);
        jLabelDegrade8.setVisible(mostrar);
    }
    
    private void jComboBoxProcedimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProcedimientosActionPerformed
        if (((String)jComboBoxProcedimientos.getSelectedItem() != "Conducción imprudente, negligente o antirreglamentaria de un vehículo con motor")
            && ((String)jComboBoxProcedimientos.getSelectedItem() != "Seleccione el procedimiento")) {
            mostrarCircExt1(false);
            jComboBoxMotivos.setSelectedItem("Seleccione el motivo");
            mostrarCircExt2(false);
            mostrarMotivos(true);
            jButtonSiguiente.setEnabled(false);
        }
        if ((String)jComboBoxProcedimientos.getSelectedItem() == "Conducción imprudente, negligente o antirreglamentaria de un vehículo con motor") {
            mostrarMotivos(false);
            jComboBoxMotivos.setSelectedItem("Seleccione el motivo");
            mostrarCircExt2(true);
            mostrarCircExt1(false);
            jButtonSiguiente.setEnabled(false);
        } 
        if ((String)jComboBoxProcedimientos.getSelectedItem() == "Seleccione el procedimiento") {
            mostrarMotivos(false);
            mostrarCircExt1(false);
            mostrarCircExt2(false);
            jButtonSiguiente.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBoxProcedimientosActionPerformed

    private void jComboBoxMotivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMotivosActionPerformed
        if ((String)jComboBoxMotivos.getSelectedItem() != "Seleccione el motivo") {
            mostrarCircExt1(true);
        }
        if ((String)jComboBoxMotivos.getSelectedItem() == "Seleccione el motivo") {
            mostrarCircExt1(false);
            jButtonSiguiente.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBoxMotivosActionPerformed

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        LesionVictimario a = new LesionVictimario();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void jRadioButtonSi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSi1ActionPerformed
        if (jRadioButtonSi1.isSelected()) {
            jButtonSiguiente.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonSi1ActionPerformed

    private void jRadioButtonNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNo1ActionPerformed
        if (jRadioButtonNo1.isSelected()) {
            jButtonSiguiente.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonNo1ActionPerformed

    private void jRadioButtonSi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSi2ActionPerformed
        if (jRadioButtonSi2.isSelected()) {
            jButtonSiguiente.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonSi2ActionPerformed

    private void jRadioButtonNo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNo2ActionPerformed
        if (jRadioButtonNo2.isSelected()) {
           jButtonSiguiente.setEnabled(true);
        }
	}//GEN-LAST:event_jRadioButtonNo2ActionPerformed

    public static String getProcedimiento() {
        String resultado = (String)jComboBoxProcedimientos.getSelectedItem();
        switch (resultado) {    
            case "Ningún procedimiento insidioso":
                resultado = "Ningun procedimiento insidioso";
                break;                
            case "Ensañamiento":
                resultado = "Ensaniamiento";
                break;                
            case "Alevosía":
                resultado = "Alevosia";
                break;
            case "Emoción violenta":
                resultado = "Emocion violenta";
                break;                
            case "Medio empleado no debería causar la muerte":
                resultado = "Medio empleado no deberia causar la muerte";
                break;                
            case "Imprudencia, negligencia o impericia en arte o profesión":
                resultado = "Imprudencia, negligencia o impericia en arte o profesion";
                break;                
            case "Conducción imprudente, negligente o antirreglamentaria de un vehículo con motor":
                resultado = "Conduccion imprudente, negligente o antirreglamentaria de un vehiculo con motor";
                break;                
        }
        return resultado;
    }    
    
    public static String getMotivo() {
        String resultado = (String)jComboBoxMotivos.getSelectedItem();
        switch (resultado) {    
            case "Odio de género":
                resultado = "Odio de genero";
                break; 
            case "Odio a la orientación sexual":
                resultado = "Odio a la orientacion sexual";
                break; 
            case "Odio a la identidad de género o su expresión":
                resultado = "Odio a la identidad de genero o su expresion";
                break;
            case "Medio idóneo para crear un peligro común":
                resultado = "Medio idoneo para crear un peligro comun";
                break;
            case "Función/cargo/condición de seguridad pública/policial/penitenciaria (de la víctima)":
                resultado = "Funcion/cargo/condicion de seguridad publica/policial/penitenciaria (de la victima)";
                break;
            case "Abuso de función/cargo de seguridad pública/policial/penitenciaria (del victimario)":
                resultado = "Abuso de funcion/cargo de seguridad publica/policial/penitenciaria (del victimario)";
                break;
            case "Violencia de género (De hombre a mujer)":
                resultado = "Violencia de genero (De hombre a mujer)";
                break;
            case "Procurar impunidad para sí u otro delito":
                resultado = "Procurar impunidad para si u otro delito";
                break;
            case "Causar daño en el cuerpo":
                resultado = "Causar danio en el cuerpo";
                break;                
        }
        return resultado;
    }   

    public static String getCircunstanciasExternasDeAtenuacion() {
        String resultado = "";
        if ((String)jComboBoxProcedimientos.getSelectedItem() != "Conducción imprudente, negligente o antirreglamentaria de un vehículo con motor") {
            if (jRadioButtonSi1.isSelected()) {
                resultado = "Si";
            }
            if (jRadioButtonNo1.isSelected()) {
                resultado = "No";
            }
        }
        if ((String)jComboBoxProcedimientos.getSelectedItem() == "Conducción imprudente, negligente o antirreglamentaria de un vehículo con motor") {
            if (jRadioButtonSi2.isSelected()) {
                resultado = "No";
            }
            if (jRadioButtonNo2.isSelected()) {
                resultado = "Si";
            }
        }
        return resultado;
    }        
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonSiguiente;
    private static javax.swing.JComboBox<String> jComboBoxMotivos;
    private static javax.swing.JComboBox<String> jComboBoxProcedimientos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCircExt;
    private javax.swing.JLabel jLabelConduccionCircExt;
    private javax.swing.JLabel jLabelDegrade1;
    private javax.swing.JLabel jLabelDegrade2;
    private javax.swing.JLabel jLabelDegrade3;
    private javax.swing.JLabel jLabelDegrade4;
    private javax.swing.JLabel jLabelDegrade5;
    private javax.swing.JLabel jLabelDegrade6;
    private javax.swing.JLabel jLabelDegrade7;
    private javax.swing.JLabel jLabelDegrade8;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLogoUNLa;
    private javax.swing.JLabel jLabelMotivo;
    private javax.swing.JLabel jLabelProcedimiento;
    private javax.swing.JLabel jLabelTitulo;
    private static javax.swing.JRadioButton jRadioButtonNo1;
    private static javax.swing.JRadioButton jRadioButtonNo2;
    private static javax.swing.JRadioButton jRadioButtonSi1;
    private static javax.swing.JRadioButton jRadioButtonSi2;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
